/**
 * Generate scripts/ch5-part-5.2.json — 100 cases for subsection 5.2 Objectives of marketing.
 */
import fs from "node:fs";
import { buildCases, validateAndWrite } from "./ch5-fc-gen-shared.mjs";

const slots = JSON.parse(fs.readFileSync("scripts/ch5-slot-plan.json", "utf8"))["5.2"];
const OUT = "scripts/ch5-part-5.2.json";

const SCENE = [
  "Consider a regional bakery that tracks repeat purchases, complaint rates, and promotional responses while setting annual marketing targets. Evaluate the following economic assertions:",
  "Consider a sportswear manufacturer investing in distinctive product design, athlete endorsements, and loyalty programmes to stand apart from rivals. Evaluate the following economic assertions:",
  "Consider a mobile network operator monitoring its subscriber share, monthly sales, and profit margins against three national competitors. Evaluate the following economic assertions:",
  "Consider a furniture retailer that surveys post-purchase satisfaction, promotes a craftsmanship guarantee, and aims to grow regional sales volume. Evaluate the following economic assertions:",
  "Consider a dairy cooperative that brands its organic milk line, measures shelf share in supermarkets, and reinvests surplus profit into processing equipment. Evaluate the following economic assertions:",
  "Consider a budget airline balancing ticket sales growth, on-board service ratings, and route-level profitability across its European network. Evaluate the following economic assertions:",
  "Consider a cosmetics firm launching a premium skincare range with a clear differentiation message and tracking customer repurchase rates. Evaluate the following economic assertions:",
  "Consider a hardware store chain comparing local market share, promotional sales spikes, and net profit after covering warehouse costs. Evaluate the following economic assertions:",
  "Consider a software provider offering a distinctive user interface, monitoring renewal rates, and pursuing higher subscription sales each quarter. Evaluate the following economic assertions:",
  "Consider a coffee roaster building brand recognition, measuring customer satisfaction scores, and targeting a larger share of the specialty segment. Evaluate the following economic assertions:",
  "Consider a car-hire company that rewards loyal renters, advertises fleet reliability as its key difference, and tracks revenue per vehicle. Evaluate the following economic assertions:",
  "Consider a pharmaceutical wholesaler expanding sales to clinics while monitoring delivery satisfaction and gross profit on each product line. Evaluate the following economic assertions:",
  "Consider a boutique hotel group emphasising personalised service, measuring guest review scores, and aiming to raise occupancy revenue. Evaluate the following economic assertions:",
  "Consider a gardening supplies distributor promoting expert advice as its unique offer while pursuing higher sales through garden-centre partners. Evaluate the following economic assertions:",
  "Consider a craft brewery that differentiates through local ingredients, tracks tap-room repeat visits, and monitors profit after production costs. Evaluate the following economic assertions:",
];

const THEORY = [
  "Analyze how businesses set marketing objectives after analysing the markets they wish to operate in. Evaluate the following economic assertions:",
  "Review the role of customer satisfaction as a marketing objective linked to repeat purchase and loyalty. Evaluate the following economic assertions:",
  "Analyze how a unique selling proposition supports product differentiation and attracts loyal customers. Evaluate the following economic assertions:",
  "Review why gaining and maintaining market share indicates a firm's relative competitiveness. Evaluate the following economic assertions:",
  "Analyze the importance of maintaining or increasing sales to cover production costs and earn profit. Evaluate the following economic assertions:",
  "Review profitability as a marketing objective and its link to reimbursing owners and reinvestment. Evaluate the following economic assertions:",
  "Analyze how customer satisfaction interrelates with other marketing objectives such as sales and loyalty. Evaluate the following economic assertions:",
  "Review how product differentiation can rest on product characteristics or on promotion and customer perception. Evaluate the following economic assertions:",
  "Analyze why building a brand supports the creation of a unique selling proposition. Evaluate the following economic assertions:",
  "Review how market share reflects a business position relative to competitors in the same market. Evaluate the following economic assertions:",
  "Analyze the relationship between higher sales figures and profitability within stated limitations. Evaluate the following economic assertions:",
  "Review why dissatisfied customers are unlikely to buy a product again. Evaluate the following economic assertions:",
  "Analyze how a unique selling proposition makes a product seem special, unique, or better than alternatives. Evaluate the following economic assertions:",
  "Review the marketing objective of maintaining sales volume to generate revenue. Evaluate the following economic assertions:",
  "Analyze how retained profit from higher sales can be reinvested in the business. Evaluate the following economic assertions:",
  "Review the interdependence of customer satisfaction, differentiation, market share, sales, and profitability objectives. Evaluate the following economic assertions:",
  "Analyze how loyal customers who buy again strengthen both sales and competitive position. Evaluate the following economic assertions:",
  "Review why businesses analyse customer wishes and needs before defining marketing objectives. Evaluate the following economic assertions:",
  "Analyze how promotion and perceived quality can underpin a product's unique selling proposition. Evaluate the following economic assertions:",
  "Review market share as an indicator of relative importance compared with rival firms. Evaluate the following economic assertions:",
  "Analyze why sales revenues must cover production costs before profit can be earned. Evaluate the following economic assertions:",
  "Review how profitability objectives relate to returns on owners' invested capital. Evaluate the following economic assertions:",
  "Analyze the objective of creating differentiation so customers view a product as unlike similar offerings. Evaluate the following economic assertions:",
  "Review satisfied customers as a foundation for loyalty and further purchases. Evaluate the following economic assertions:",
  "Analyze how competitive firms monitor share, sales, and profit when setting marketing goals. Evaluate the following economic assertions:",
  "Review the limitation that higher sales do not automatically guarantee higher profit in every circumstance. Evaluate the following economic assertions:",
  "Analyze how a clear unique selling proposition helps attract many loyal customers. Evaluate the following economic assertions:",
  "Review customer satisfaction as an objective that supports retention rather than one-off transactions. Evaluate the following economic assertions:",
  "Analyze market share maintenance as a competitiveness indicator in contested markets. Evaluate the following economic assertions:",
  "Review sales growth objectives in relation to covering costs and sustaining operations. Evaluate the following economic assertions:",
  "Analyze profitability as an outcome owners seek through effective marketing and sales performance. Evaluate the following economic assertions:",
  "Review how product characteristics and promotional messaging jointly shape differentiation. Evaluate the following economic assertions:",
  "Analyze why marketing objectives extend beyond a single measure such as sales volume alone. Evaluate the following economic assertions:",
  "Review the link between meeting customer needs and achieving repeat purchase behaviour. Evaluate the following economic assertions:",
  "Analyze how a business positions itself as better than the rest through a credible unique selling proposition. Evaluate the following economic assertions:",
  "Review relative market share comparisons among firms serving the same customer base. Evaluate the following economic assertions:",
  "Analyze revenue from sales as the flow that must exceed costs for profit to arise. Evaluate the following economic assertions:",
  "Review reinvestment of profit as a reason owners pursue profitable marketing outcomes. Evaluate the following economic assertions:",
  "Analyze customer loyalty as a consequence of sustained satisfaction with the product offering. Evaluate the following economic assertions:",
  "Review unique selling propositions as drivers of perceived uniqueness in crowded product categories. Evaluate the following economic assertions:",
  "Analyze maintaining market share when rivals intensify promotional competition. Evaluate the following economic assertions:",
  "Review increasing sales as a means to strengthen financial capacity without ignoring cost structures. Evaluate the following economic assertions:",
  "Analyze profitability limitations when sales rise but margins or costs move unfavourably. Evaluate the following economic assertions:",
  "Review the marketing framework in which satisfaction, differentiation, share, sales, and profit coexist. Evaluate the following economic assertions:",
  "Analyze how dissatisfaction leads customers to withhold repeat purchases. Evaluate the following economic assertions:",
  "Review brand-building activities that reinforce a product's differentiated identity. Evaluate the following economic assertions:",
  "Analyze market share gains as evidence of improved relative standing among competitors. Evaluate the following economic assertions:",
  "Review sales objectives as necessary but not sufficient for long-term financial success alone. Evaluate the following economic assertions:",
  "Analyze profit retention as internal funding for future marketing and production activity. Evaluate the following economic assertions:",
  "Review customer satisfaction surveys as inputs to marketing objective setting. Evaluate the following economic assertions:",
  "Analyze differentiation based on how customers perceive the product after promotional exposure. Evaluate the following economic assertions:",
  "Review competitiveness indicators that include share of total market sales. Evaluate the following economic assertions:",
  "Analyze the revenue requirement that sales must meet or exceed production costs. Evaluate the following economic assertions:",
  "Review owner reimbursement through profit distributions and retained earnings. Evaluate the following economic assertions:",
  "Analyze loyalty programmes as tools supporting satisfaction and repeat purchase objectives. Evaluate the following economic assertions:",
  "Review product uniqueness claims that distinguish an offering from similar substitutes. Evaluate the following economic assertions:",
  "Analyze defensive marketing aimed at holding share against aggressive rivals. Evaluate the following economic assertions:",
  "Review volume targets that align with revenue and cost coverage goals. Evaluate the following economic assertions:",
  "Analyze profit objectives within the broader set of marketing aims a business may pursue. Evaluate the following economic assertions:",
  "Review how wishes and needs analysis precedes selecting measurable marketing objectives. Evaluate the following economic assertions:",
  "Analyze perceived quality as a basis for differentiation alongside tangible product features. Evaluate the following economic assertions:",
  "Review relative share metrics when comparing firms of different absolute sales sizes. Evaluate the following economic assertions:",
  "Analyze the sales-profit relationship subject to cost and pricing constraints. Evaluate the following economic assertions:",
  "Review satisfied customers who may recommend the product to others, extending marketing impact. Evaluate the following economic assertions:",
  "Analyze unique selling propositions that rest on delivery speed, design, or service elements. Evaluate the following economic assertions:",
  "Review market share erosion as a signal of weakened competitive position. Evaluate the following economic assertions:",
  "Analyze sales campaigns designed to raise revenue while monitoring unit profitability. Evaluate the following economic assertions:",
  "Review profit reinvestment as a strategic use of earnings retained in the business. Evaluate the following economic assertions:",
  "Analyze the objective hierarchy in which satisfaction supports loyalty and subsequent sales. Evaluate the following economic assertions:",
  "Review differentiation strategies that make similar products appear distinct to buyers. Evaluate the following economic assertions:",
  "Analyze share maintenance when entering mature markets with established competitors. Evaluate the following economic assertions:",
  "Review revenue growth objectives tied to covering fixed and variable production costs. Evaluate the following economic assertions:",
  "Analyze profitability as valued by owners who provided capital to fund operations. Evaluate the following economic assertions:",
  "Review post-purchase satisfaction as a predictor of whether customers return. Evaluate the following economic assertions:",
  "Analyze promotional differentiation that shapes how customers classify the product mentally. Evaluate the following economic assertions:",
  "Review competitive benchmarking through market share alongside sales and profit trends. Evaluate the following economic assertions:",
  "Analyze sales volume increases that strengthen cash inflows before profit is calculated. Evaluate the following economic assertions:",
  "Review limitations on the sales-profit link when discounting or costs offset volume gains. Evaluate the following economic assertions:",
  "Analyze interrelated marketing objectives that reinforce one another across the customer lifecycle. Evaluate the following economic assertions:",
  "Review loyalty as an outcome when satisfaction leads customers to buy the product again. Evaluate the following economic assertions:",
  "Analyze unique selling propositions that position a product as better than the rest in buyers' minds. Evaluate the following economic assertions:",
  "Review market share as a relative measure rather than an absolute sales total alone. Evaluate the following economic assertions:",
  "Analyze maintaining sales as essential for ongoing revenue to fund business activity. Evaluate the following economic assertions:",
  "Review profitability enabling owners to be reimbursed and the firm to retain funds internally. Evaluate the following economic assertions:",
];

const TITLES = [
  "Marketing Objectives Overview",
  "Customer Satisfaction and Loyalty",
  "Unique Selling Proposition Basics",
  "Market Share as Competitiveness",
  "Sales Volume and Revenue",
  "Profitability Objective Foundations",
  "Interrelated Marketing Goals",
  "Differentiation Through Branding",
  "Satisfaction and Repeat Purchase",
  "USP and Loyal Customer Attraction",
  "Relative Market Importance",
  "Sales Covering Production Costs",
  "Profit Reinvestment Rationale",
  "Dissatisfaction and Lost Sales",
  "Perceived Product Uniqueness",
  "Share Maintenance Strategies",
  "Revenue Growth Objectives",
  "Sales-Profit Relationship Limits",
  "Customer Needs Analysis First",
  "Promotion-Based Differentiation",
  "Competitive Share Indicators",
  "Owner Reimbursement Through Profit",
  "Loyalty From Satisfied Buyers",
  "Characteristic-Based USP Claims",
  "Market Position Relative to Rivals",
  "Maintaining Sales Volume",
  "Higher Sales and Profit Link",
  "Marketing Objective Interdependence",
  "Brand Support for Differentiation",
  "Repeat Purchase Behaviour",
  "Attracting Loyal Customers",
  "Share as Competitiveness Signal",
  "Revenue Versus Cost Coverage",
  "Retained Profit for Growth",
  "Satisfaction Survey Insights",
  "Perception and Product Differentiation",
  "Benchmarking Market Share",
  "Volume Targets and Margins",
  "Profit Within Objective Set",
  "Wishes and Needs Before Objectives",
  "Quality Perception and USP",
  "Relative Share Comparisons",
  "Cost Constraints on Profitability",
  "Recommendation From Satisfied Customers",
  "Service Elements in USP",
  "Share Erosion Warning Signs",
  "Campaign Revenue Monitoring",
  "Strategic Profit Retention",
  "Satisfaction Supporting Sales",
  "Distinct Identity in Crowded Markets",
  "Mature Market Share Defence",
  "Fixed and Variable Cost Coverage",
  "Capital Providers and Profit",
  "Post-Purchase Satisfaction Predictors",
  "Mental Product Classification",
  "Share Sales Profit Trends",
  "Cash Inflow From Volume",
  "Discounting Offsetting Volume Gains",
  "Lifecycle Marketing Objectives",
  "Buy-Again Loyalty Outcomes",
  "Better Than the Rest Positioning",
  "Relative Not Absolute Share",
  "Ongoing Revenue From Sales",
  "Internal Fund Retention",
  "Single Objective Trap Cases",
  "USP Misclassification Traps",
  "Share Versus Absolute Sales",
  "Profit Without Sales Trap",
  "Satisfaction Isolation Errors",
  "Differentiation Definition Traps",
  "Market Share Purpose Errors",
  "Sales Alone Sufficiency Traps",
  "Profitability Link Misstatements",
  "Loyalty Without Satisfaction",
  "Brand Versus USP Confusion",
  "Competitor Share Comparisons",
  "Cost Coverage Misunderstandings",
  "Reinvestment Objective Errors",
  "Repeat Purchase Denials",
  "Promotion-Only Differentiation",
  "Share Maintenance Denials",
  "Volume Profit Assumptions",
  "Objective Hierarchy Mistakes",
  "Customer Needs Neglect",
  "Perceived Uniqueness Denials",
  "Competitiveness Indicator Traps",
  "Revenue Flow Assertions",
  "Owner Return Misconceptions",
  "Satisfaction Sales Interlink",
  "USP Loyalty Connection",
  "Relative Importance Measures",
  "Production Cost Coverage",
  "Profit Limitation Awareness",
  "Integrated Marketing Objective Review",
  "Closing Objective Distinctions",
  "Final Marketing Goals Assessment",
  "Comprehensive Objective Assertions",
  "Late-Stage USP and Share Cases",
  "Terminal Profit and Sales Review",
];

const sceneIndices = [
  1, 4, 7, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72,
];

// --- TRUE statements (≥300 needed; 300 used) ---
const TRUE = [
  // Customer satisfaction (60)
  ["If customers are not satisfied with the product, they are unlikely to buy it again.", "Dissatisfied customers typically withhold repeat purchases, which is why satisfaction is a core marketing objective."],
  ["Satisfied customers often become loyal customers who may purchase the product again.", "Satisfaction frequently leads to loyalty and repeat buying behaviour."],
  ["Customer satisfaction as a marketing objective is interrelated with objectives such as sales and loyalty.", "The text links satisfaction to other marketing goals rather than treating it in isolation."],
  ["Meeting customer wishes and needs is a prerequisite for defining meaningful marketing objectives.", "Businesses analyse wishes and needs before clarifying the objectives they pursue."],
  ["A business that ignores customer satisfaction risks losing repeat sales from otherwise viable buyers.", "Unsatisfied customers tend not to return, undermining sales and loyalty objectives."],
  ["Post-purchase satisfaction influences whether a customer considers the product for a future purchase.", "Future purchase intent is tied to how satisfied the customer felt after buying."],
  ["Loyal customers who buy again help sustain sales volume over time.", "Repeat purchases from loyal customers support the sales objective."],
  ["Customer satisfaction supports retention rather than relying solely on one-off transactions.", "Satisfaction aims at ongoing relationships, not isolated single purchases."],
  ["Satisfied customers may recommend the product to others, extending marketing impact beyond the original sale.", "Positive satisfaction can generate word-of-mouth that supports sales growth."],
  ["Marketing objectives include ensuring customers are content enough to consider repurchasing.", "Repurchase potential is linked to satisfaction in the marketing objectives framework."],
  ["Dissatisfied customers are a signal that marketing and product delivery may be missing stated objectives.", "Persistent dissatisfaction indicates objectives around satisfaction are not being met."],
  ["Customer satisfaction surveys can inform how well a business is meeting its marketing objectives.", "Feedback instruments help assess progress toward satisfaction goals."],
  ["A firm pursuing loyalty must first address whether customers are satisfied with the core product.", "Loyalty generally builds on satisfaction with what was purchased."],
  ["Repeat purchase behaviour is more likely when prior use met or exceeded customer expectations.", "Expectations met through satisfactory experience encourage buying again."],
  ["Customer satisfaction is not separable from long-run sales performance in the marketing framework.", "The text presents satisfaction as interrelated with sales and other objectives."],
  ["Businesses analyse customer wishes and needs because unsatisfied buyers will not sustain demand.", "Understanding needs helps avoid the outcome where buyers refuse repeat purchase."],
  ["Satisfaction objectives aim to convert first-time buyers into customers who return.", "The satisfaction objective supports turning initial purchases into repeat business."],
  ["A marketing plan that achieves high satisfaction can reinforce market share by retaining buyers.", "Retained satisfied buyers help maintain share against competitors."],
  ["Customer complaints rising over time suggest the satisfaction objective is not being achieved.", "Elevated complaints indicate failure relative to the satisfaction goal."],
  ["Satisfied customers provide a foundation for brand loyalty programmes to succeed.", "Loyalty initiatives work best when underlying satisfaction is already present."],
  ["If a product fails to meet needs, marketing objectives around sales growth become harder to reach.", "Unmet needs undermine sales because buyers avoid repeat purchase."],
  ["Satisfaction with product quality can encourage customers to choose the same brand on the next occasion.", "Quality satisfaction supports brand-level repeat choice."],
  ["Marketing objectives treat customer satisfaction as linked to maintaining competitive sales.", "Satisfaction and sales objectives are presented as interrelated."],
  ["A business measuring repurchase rates is indirectly tracking success on satisfaction objectives.", "Repurchase frequency reflects whether customers remain satisfied."],
  ["Customers who feel their wishes were fulfilled are more willing to buy the product again.", "Fulfilled wishes support the repeat purchase outcome described in the text."],
  ["Satisfaction objectives complement differentiation by ensuring the promised uniqueness is experienced.", "Customers must be satisfied with the differentiated offer for loyalty to follow."],
  ["Poor satisfaction can erode market share even when promotional spending remains high.", "Dissatisfied customers may switch to rivals, reducing relative share."],
  ["Satisfaction is an objective because unhappy customers simply will not buy the product again.", "The text states dissatisfied customers will not buy again."],
  ["Loyalty outcomes depend on customers having a satisfactory experience with prior purchases.", "Loyalty in the framework follows from satisfactory prior buying experiences."],
  ["Businesses set satisfaction targets because loyal repeat buyers strengthen several other objectives.", "Loyal repeat buyers support sales, share, and profitability aims."],
  ["Meeting needs analysed in the market helps a firm align its product with satisfaction goals.", "Market analysis of wishes and needs supports satisfaction objectives."],
  ["A satisfied customer base reduces reliance on constant new-customer acquisition alone.", "Retention of satisfied buyers supplements acquisition in meeting sales goals."],
  ["Customer satisfaction is one of several marketing objectives a business may pursue.", "The text lists satisfaction among multiple possible marketing objectives."],
  ["Satisfaction contributes to profitability indirectly by supporting repeat revenue streams.", "Repeat revenue from satisfied customers can support profit objectives."],
  ["When customers are satisfied, they are more likely to remain with the firm rather than switch.", "Satisfaction reduces switching, helping maintain share and sales."],
  ["Marketing staff may track satisfaction scores alongside sales when reviewing objective performance.", "Satisfaction metrics complement sales data in objective review."],
  ["A product that delights customers on first use is better positioned to achieve loyalty objectives.", "Positive first-use experience supports subsequent loyalty."],
  ["Dissatisfaction after a promotional trial can undo short-term sales gains from the campaign.", "Temporary sales spikes fail if buyers are dissatisfied and do not return."],
  ["Satisfaction objectives encourage firms to deliver what was promised in differentiation messaging.", "Delivering on promises links satisfaction to credible USP claims."],
  ["Repeat visits to a retailer by the same household suggest satisfaction objectives are being met.", "Household repeat visits indicate ongoing satisfaction."],
  ["Customer satisfaction is interrelated with profitability because loyal buyers generate recurring revenue.", "Recurring revenue from loyal buyers can support profit aims."],
  ["Firms that prioritise satisfaction still pursue other objectives such as market share and sales.", "Satisfaction is one objective among several, not the only one."],
  ["A decline in satisfaction ratings may precede a fall in relative market share.", "Falling satisfaction can foreshadow share loss to rivals."],
  ["Satisfied customers are more receptive to extensions of a product line from the same business.", "Satisfaction with the core offer supports acceptance of related products."],
  ["The marketing objectives framework assumes satisfied customers may buy again.", "Repeat purchase from satisfied customers is explicitly noted."],
  ["Businesses failing on satisfaction will struggle to build the loyal customer base a USP aims to attract.", "USP objectives assume satisfaction sustains the loyalty USP is meant to create."],
  ["Customer wishes and needs analysis helps set realistic satisfaction targets.", "Understanding needs informs what satisfaction should look like."],
  ["Satisfaction with after-sales service can reinforce overall marketing objective achievement.", "Service satisfaction supports broader objective success."],
  ["A loyal customer who buys again reduces the average cost of acquiring each unit sold.", "Repeat buyers lower effective acquisition cost, aiding profitability."],
  ["Marketing objectives on satisfaction aim to prevent customers from abandoning the product.", "Preventing abandonment through satisfaction supports retention."],
  ["High satisfaction can stabilise sales when competitors launch aggressive price promotions.", "Loyal satisfied buyers may resist switching on price alone."],
  ["Satisfaction measurement helps a business know whether differentiation claims match customer experience.", "Feedback reveals whether perceived differentiation is experienced as satisfactory."],
  ["Customers not satisfied with one product in a range may avoid other products from the same firm.", "Dissatisfaction can spread wariness across the firm's offerings."],
  ["Satisfaction objectives align with the idea that marketing must fulfil wishes and needs.", "Fulfilling wishes and needs is the broader aim satisfaction supports."],
  ["A satisfied customer is a candidate for becoming a loyal customer in the textbook framework.", "Satisfaction often precedes loyalty in the described relationship."],
  ["Repeat purchase is a behavioural sign that satisfaction and loyalty objectives are progressing.", "Repurchase signals progress on satisfaction-linked loyalty."],
  ["Satisfaction supports market share maintenance by keeping existing buyers from leaving.", "Retained buyers help hold share against competitors."],
  ["Businesses treat satisfaction as strategically linked to sales volume over multiple periods.", "Multi-period sales benefit when satisfaction drives repeat buying."],
  ["Without satisfactory delivery, differentiation claims may fail to produce loyal customers.", "USP attraction of loyal customers assumes satisfactory product experience."],
  ["Customer satisfaction is presented as interrelated with the objective of increasing sales.", "Satisfaction and sales objectives reinforce each other in the text."],
  ["A firm improving satisfaction may see improved retention metrics in subsequent quarters.", "Better satisfaction can show up as higher retention over time."],
  // USP / differentiation (60)
  ["A unique selling proposition means a product is or is considered different from similar products.", "USP is defined as actual or perceived difference from similar offerings."],
  ["Product differentiation can be based on a characteristic of the product itself.", "Differentiation may rest on tangible product features."],
  ["Product differentiation can also arise from the way a product is promoted and perceived by customers.", "Promotion and perception are valid bases for differentiation."],
  ["Building a brand supports creating a unique selling proposition for the product.", "Brand-building is explicitly linked to USP creation."],
  ["A product with a USP may seem special, unique, or better than the rest to customers.", "USP positions the product as distinctive or superior in customer perception."],
  ["Businesses create a USP because it helps attract many loyal customers.", "USP is pursued to draw loyal customers to the offering."],
  ["Product differentiation is another term for the positioning achieved through a unique selling proposition.", "Differentiation and USP are treated as related concepts."],
  ["A USP can rest on design features that rivals' similar products do not emphasise.", "Design emphasis can underpin differentiation."],
  ["Promotional messaging can shape how customers perceive a product's uniqueness.", "Perception shaped by promotion supports USP."],
  ["Brand identity helps customers recognise why one product differs from close substitutes.", "Brand identity reinforces differentiated recognition."],
  ["A credible USP makes similar products appear distinct in the buyer's mind.", "USP creates mental distinction among similar products."],
  ["Differentiation through service quality can form part of a product's unique selling proposition.", "Service quality may be the differentiating characteristic."],
  ["A firm investing in brand advertising may be pursuing a USP objective.", "Brand advertising supports USP-related differentiation."],
  ["USP objectives aim to reduce direct comparability with undifferentiated rivals on price alone.", "Differentiation moves competition beyond pure price comparison."],
  ["Customers may perceive uniqueness even when products share many functional similarities.", "Perceived uniqueness can exist alongside functional similarity."],
  ["A unique selling proposition can highlight delivery speed as the distinguishing element.", "Delivery speed may serve as the USP characteristic."],
  ["Packaging design can contribute to differentiation and support a USP.", "Packaging may be part of the differentiated presentation."],
  ["A USP based on ethical sourcing can differentiate a product in a crowded category.", "Ethical sourcing claims can underpin differentiation."],
  ["Product differentiation helps a business stand out when many similar alternatives exist.", "Differentiation addresses crowded markets with similar options."],
  ["Brand loyalty programmes often accompany products with a clear unique selling proposition.", "Loyalty programmes complement USP-driven differentiation."],
  ["A USP may emphasise durability as the product characteristic that sets it apart.", "Durability can be the differentiating product characteristic."],
  ["Promotion that stresses craftsmanship can build a perceived USP for handmade goods.", "Craftsmanship messaging supports perceived differentiation."],
  ["Differentiation objectives encourage customers to view the offer as unlike substitutes.", "The aim is distinct perception versus substitutes."],
  ["A strong brand can make customers believe a product is better than the rest.", "Brand strength supports better-than-the-rest perception."],
  ["USP creation is a recognised marketing objective in the textbook overview.", "USP is listed among marketing objectives businesses may pursue."],
  ["Differentiation through warranty terms can form a valid unique selling proposition.", "Warranty terms may differentiate the offering."],
  ["A product considered unique may command buyer attention despite numerous rivals.", "Perceived uniqueness draws attention in competitive markets."],
  ["Brand-building and USP objectives work together to attract loyal repeat buyers.", "Brand and USP jointly support loyal customer attraction."],
  ["A USP may rest on how the product is experienced after purchase, not only on pre-purchase claims.", "Post-purchase experience can sustain differentiation."],
  ["Promotional differentiation shapes customer perception even before the first purchase.", "Pre-purchase perception is shaped by promotion."],
  ["Businesses pursue differentiation because similar products without a USP compete mainly on price.", "Without USP, price becomes the primary competitive lever."],
  ["A unique selling proposition can highlight environmental credentials as the distinguishing factor.", "Environmental credentials may underpin the USP."],
  ["Product lines may each carry a distinct USP within the same corporate brand.", "Different USPs can apply across product lines under one brand."],
  ["Differentiation based on customer support quality can attract buyers who value assistance.", "Support quality may be the differentiating element."],
  ["A USP makes the product or seems to make the product unlike other similar offerings.", "USP creates actual or apparent difference from similar products."],
  ["Brand investment is a marketing activity that supports USP objectives.", "Brand investment is linked to USP creation in the text."],
  ["Differentiation can rely on a single prominent characteristic promoted consistently.", "One promoted characteristic can anchor the USP."],
  ["A perceived USP can persist through consistent branding across multiple channels.", "Consistent branding sustains perceived differentiation."],
  ["USP objectives interrelate with satisfaction because customers must experience the claimed difference.", "Experienced difference links USP to satisfaction outcomes."],
  ["A product differentiation strategy may target buyers who seek premium perceived quality.", "Premium quality perception can be the differentiation target."],
  ["Marketing objectives on USP aim to make the firm's offer memorable versus rivals.", "Memorable distinction is a USP outcome."],
  ["Differentiation through local sourcing can be promoted as a unique selling proposition.", "Local sourcing may be promoted as the USP."],
  ["A USP helps attract loyal customers who identify with the brand's differentiated identity.", "Brand identity alignment attracts loyal buyers."],
  ["Product differentiation is pursued so the product appears special relative to the rest.", "Special appearance relative to alternatives is a USP aim."],
  ["Promotional emphasis on innovation can support a USP in technology categories.", "Innovation messaging can underpin differentiation."],
  ["Brand reputation accumulated over time reinforces the product's unique selling proposition.", "Reputation reinforces ongoing USP credibility."],
  ["A USP may combine a product feature with a distinctive promotional style.", "Features and promotional style can jointly form the USP."],
  ["Differentiation objectives are listed alongside satisfaction and market share objectives.", "USP/differentiation sits among the stated marketing objectives."],
  ["Customers comparing similar products may rely on USP cues to make a choice.", "USP cues guide choice among similar products."],
  ["A business without differentiation may struggle to attract loyal customers in a saturated market.", "Saturated markets make USP important for loyal customer attraction."],
  ["Building a brand is a means to an end of creating perceived product uniqueness.", "Brand-building serves perceived uniqueness objectives."],
  ["A USP based on customisation options differentiates a standard product category offering.", "Customisation can differentiate within a standard category."],
  ["Differentiation through perceived exclusivity can support premium pricing objectives.", "Exclusivity perception can accompany premium positioning."],
  ["USP messaging must align with what customers ultimately experience to sustain loyalty.", "Aligned experience sustains loyalty promised by USP."],
  ["Product differentiation reduces the product's substitutability in the customer's view.", "Differentiation lowers perceived substitutability."],
  ["A unique selling proposition can highlight reliability as the key product characteristic.", "Reliability may be the highlighted differentiating characteristic."],
  ["Brand symbols and logos help communicate the differentiated identity of the product.", "Visual brand elements communicate differentiation."],
  ["Marketing spend on differentiation supports the objective of seeming better than alternatives.", "Differentiation spend targets better-than-alternatives perception."],
  ["A USP created through promotion still counts as differentiation in the marketing framework.", "Promotion-based differentiation is explicitly recognised."],
  ["Differentiation and USP objectives connect to attracting a loyal customer following.", "USP aims to attract many loyal customers per the text."],
  // Market share (60)
  ["Gaining and maintaining market share is a marketing objective for many businesses.", "Market share is listed among marketing objectives."],
  ["Market share indicates a firm's relative importance in the market compared with competitors.", "Share reflects relative standing versus rivals."],
  ["Market share serves as an indicator of competitiveness in the marketing framework.", "Share is described as a competitiveness indicator."],
  ["Businesses compare their share with competitors' positions in the same market.", "Share is assessed relative to competitor positions."],
  ["A rising market share may signal improved performance relative to rival firms.", "Share gains suggest improved relative performance."],
  ["Maintaining market share can be an explicit marketing objective during intense rivalry.", "Share maintenance is a valid stated objective."],
  ["Market share reflects the firm's portion of total sales in the defined market.", "Share is a portion of total market sales."],
  ["Losing market share may indicate weakened competitiveness against other suppliers.", "Share loss signals weakened relative competitiveness."],
  ["Marketing campaigns may aim to protect share when a new competitor enters.", "Defensive campaigns can target share protection."],
  ["Market share objectives complement sales objectives by adding a relative dimension.", "Share adds relative context to absolute sales."],
  ["A firm with small absolute sales may still hold a significant share in a niche market.", "Share can be significant even with modest absolute sales in niches."],
  ["Competitiveness is partly assessed through how market share changes over time.", "Share trends inform competitiveness assessment."],
  ["Businesses interested in market share want to know their position versus rivals.", "Share answers relative position questions."],
  ["Gaining share often requires taking customers from competing firms.", "Share gains typically come at rivals' expense."],
  ["Market share is a relative measure rather than an absolute sales total alone.", "Share is inherently relative to the market total."],
  ["A stable market share in a growing market may still mean rising absolute sales.", "Stable share can coexist with rising absolute sales in growing markets."],
  ["Marketing objectives may target a minimum share threshold to remain competitive.", "Minimum share targets express competitiveness aims."],
  ["Share analysis helps managers understand competitive dynamics in their industry.", "Share data illuminates industry competitive dynamics."],
  ["A business defending share may increase promotional spending when rivals gain ground.", "Promotional response can aim at share defence."],
  ["Market share objectives are interrelated with satisfaction and differentiation goals.", "Share links to other objectives in the framework."],
  ["Relative importance in the market is what market share is designed to indicate.", "Share indicates relative market importance per the text."],
  ["Two firms with equal absolute sales may have different shares if market sizes differ.", "Share depends on market total, not absolute sales alone."],
  ["A firm tracking share monthly is monitoring a competitiveness indicator.", "Regular share tracking monitors competitiveness."],
  ["Market share maintenance is harder when differentiated rivals win satisfied loyal buyers.", "Rival differentiation and loyalty challenge share maintenance."],
  ["Share objectives encourage attention to competitor actions, not only internal sales.", "Share focus requires competitor awareness."],
  ["A market leader's share position signals its relative importance among industry firms.", "Leaders' share shows relative industry importance."],
  ["Marketing plans may set share targets alongside volume and profit goals.", "Share sits alongside volume and profit in planning."],
  ["Declining share despite rising sales can occur if the overall market grows faster.", "Fast market growth can lower share even as sales rise."],
  ["Competitiveness indicators include whether share is holding steady against key rivals.", "Steady share against rivals indicates competitive holding."],
  ["Businesses analyse markets partly to estimate achievable share objectives.", "Market analysis informs realistic share targets."],
  ["A new entrant's share gain comes at the expense of incumbents' relative positions.", "Entrant gains redistribute relative share."],
  ["Market share is compared among firms serving the same customer base.", "Share comparisons use the same market boundary."],
  ["Holding share in a declining market may require gaining sales while the total shrinks.", "Shrinking markets make share defence demanding."],
  ["Share objectives motivate firms to monitor rival promotional and pricing moves.", "Rival moves matter for share objectives."],
  ["A firm's relative importance falls when its market share declines.", "Share decline reduces indicated relative importance."],
  ["Marketing staff may present share charts to show competitiveness trends to management.", "Share charts communicate competitiveness trends."],
  ["Gaining share can strengthen negotiating power with distributors in some industries.", "Higher share can improve channel negotiating position."],
  ["Share is an objective because it summarises standing versus competitors.", "Share summarises competitive standing."],
  ["Satisfied loyal customers help a firm maintain its market share against rivals.", "Loyal satisfied buyers support share maintenance."],
  ["A USP that attracts loyal buyers can support market share objectives.", "USP-driven loyalty can underpin share gains or defence."],
  ["Market share data is used to benchmark performance against the competitive set.", "Share benchmarks performance within the competitive set."],
  ["Relative share comparisons matter more than isolated internal sales figures for competitiveness.", "Competitiveness assessment uses relative share."],
  ["A business may sacrifice short-term profit to invest in share gains.", "Share investment may temporarily reduce profit."],
  ["Share erosion to a rival with a stronger USP signals differentiation weakness.", "Share loss to a differentiated rival signals competitive pressure."],
  ["Maintaining share is a marketing objective distinct from merely raising absolute sales.", "Share maintenance differs from absolute sales growth alone."],
  ["Market share reflects how much of the market's total sales the firm captures.", "Captured portion of market sales defines share."],
  ["Competitiveness improves when a firm gains share while rivals lose ground.", "Relative share shift indicates improved competitiveness."],
  ["Share targets are set after analysing the market the business wants to operate in.", "Market analysis precedes share objective setting."],
  ["A firm with declining satisfaction may see market share fall as customers switch.", "Dissatisfaction-driven switching reduces share."],
  ["Marketing objectives on share align with wanting a certain portion of market sales.", "Share objectives express desired market portion."],
  ["Industry reports ranking firms by share illustrate relative importance.", "Share rankings show relative importance among firms."],
  ["Defensive marketing aims to stop share loss to aggressive competitors.", "Defensive efforts target share stabilisation."],
  ["Share and sales objectives together give absolute and relative performance views.", "Sales and share provide complementary performance lenses."],
  ["A competitiveness review typically examines market share alongside rival trends.", "Competitiveness reviews include share and rival data."],
  ["Gaining share in a mature market often requires taking customers from established rivals.", "Mature markets require share taken from incumbents."],
  ["Market share is an indicator, not a substitute for profitability analysis.", "Share indicates competitiveness but does not replace profit analysis."],
  ["Businesses monitor share because it shows position relative to competitors' positions.", "Share shows position relative to rivals."],
  ["A marketing objective to grow share implies outperforming rivals in relative terms.", "Share growth means relative outperformance."],
  ["Share maintenance can be supported by customer loyalty built through satisfaction.", "Loyalty from satisfaction aids share defence."],
  ["Relative importance in the market is the concept market share is meant to convey.", "Share conveys relative market importance."],
  // Sales volume (60)
  ["Maintaining or increasing sales is a marketing objective because sales generate revenue.", "Sales objectives exist because sales produce revenue."],
  ["Sales are important to businesses because revenues must cover production costs.", "Revenue from sales must cover production costs."],
  ["Sales revenue contributes to the ability to make a profit after costs are met.", "After covering costs, sales revenue enables profit."],
  ["A business pursuing higher sales aims to strengthen its revenue inflow.", "Higher sales strengthen revenue inflow."],
  ["Marketing campaigns often target a sales volume increase in a defined period.", "Campaigns commonly set period sales volume targets."],
  ["Sales objectives may be stated in units sold or in revenue terms.", "Volume can be measured in units or revenue."],
  ["Without adequate sales, a business cannot cover its production costs from revenue.", "Insufficient sales leave costs uncovered by revenue."],
  ["Increasing sales is listed among marketing objectives businesses may pursue.", "Sales growth is a recognised marketing objective."],
  ["Seasonal sales peaks may still align with an overall objective to increase annual volume.", "Seasonal peaks contribute to annual volume objectives."],
  ["Sales growth supports cash inflows needed for day-to-day operations.", "Higher sales improve operational cash inflows."],
  ["A promotional discount may be used to lift short-term sales volume.", "Discounts can temporarily raise sales volume."],
  ["Sales targets are set after analysing the market the firm wishes to serve.", "Market analysis informs sales target setting."],
  ["Revenue from sales must exceed production costs for profit to be possible.", "Profit requires sales revenue above production costs."],
  ["Maintaining sales volume can be an objective when a market matures.", "Mature markets may emphasise volume maintenance."],
  ["Sales performance is monitored to assess progress toward marketing objectives.", "Sales monitoring tracks objective progress."],
  ["A decline in unit sales may signal failure on sales-related marketing objectives.", "Falling unit sales indicate missed sales objectives."],
  ["Higher sales figures usually support profitability, subject to stated limitations.", "Higher sales generally support profit with noted limitations."],
  ["Sales objectives interrelate with customer satisfaction because repeat buyers add volume.", "Repeat buyers from satisfaction add to sales volume."],
  ["Distribution expansion may be pursued to increase sales to new geographic areas.", "Geographic expansion can raise sales volume."],
  ["A firm may set quarterly sales targets as part of its marketing plan.", "Quarterly targets operationalise sales objectives."],
  ["Sales volume growth in a new product launch is a common marketing objective.", "Launch campaigns often target volume growth."],
  ["Revenue coverage of costs is why sales matter beyond mere activity measures.", "Sales matter because they fund cost coverage."],
  ["Wholesale and retail channels both contribute to the firm's total sales volume.", "Channel sales aggregate into total volume."],
  ["A sales objective to maintain volume may apply when supply constraints cap growth.", "Supply limits can shift focus to maintenance."],
  ["Marketing spend on advertising may aim to raise sales of a specific product line.", "Advertising can target line-level sales increases."],
  ["Unit sales growth contributes to the revenue pool from which costs are paid.", "Unit growth enlarges the revenue pool for costs."],
  ["Sales data helps managers see whether marketing objectives are being achieved.", "Sales data indicates objective achievement."],
  ["A business with rising sales but rising costs may still miss profit objectives.", "Sales growth does not guarantee profit if costs rise."],
  ["Maintaining sales is essential for ongoing revenue to fund business activity.", "Ongoing activity requires maintained sales revenue."],
  ["Sales objectives complement share objectives by measuring absolute performance.", "Absolute sales complement relative share measures."],
  ["Promotional bundles may be introduced to stimulate higher sales volume quickly.", "Bundles can stimulate short-term volume."],
  ["Sales revenue flows from customers purchasing the product in the market.", "Customer purchases generate sales revenue."],
  ["A marketing plan without sales targets would omit a core objective category.", "Sales targets belong in comprehensive marketing plans."],
  ["Volume sold through online channels counts toward overall sales objectives.", "Online channel sales count in total volume."],
  ["Sales growth from loyal repeat customers is a sustainable volume source.", "Loyal repeat buyers sustainably add volume."],
  ["Production must be aligned with sales objectives to avoid unmet demand or excess stock.", "Operations align with sales objective levels."],
  ["A temporary sales spike from a campaign still counts toward period volume objectives.", "Campaign spikes contribute to period volume."],
  ["Sales cover variable and fixed production costs when revenue is sufficient.", "Sufficient revenue covers both cost types."],
  ["Marketing staff may compare actual sales to targeted sales each month.", "Monthly actual-versus-target comparison tracks sales objectives."],
  ["Increasing sales in export markets can be a marketing objective for growth.", "Export growth is a valid sales objective."],
  ["Sales volume objectives may be adjusted after market analysis reveals demand limits.", "Demand analysis can revise volume targets."],
  ["A price reduction might raise unit sales while affecting revenue per unit.", "Price cuts can raise units while changing revenue per unit."],
  ["Sales are important because they provide the funds to cover production costs and profit.", "Sales fund costs and enable profit per the text."],
  ["Volume targets at retail level roll up to manufacturer sales objectives.", "Retail volume aggregates to supplier sales."],
  ["A business may prioritise sales growth when entering a new customer segment.", "New segments often trigger sales growth focus."],
  ["Sales performance relative to plan indicates marketing effectiveness.", "Plan variance shows marketing effectiveness."],
  ["Revenue objectives are closely tied to sales volume and selling price.", "Revenue depends on volume and price together."],
  ["Maintaining sales during an economic downturn can be a demanding marketing objective.", "Downturns make sales maintenance challenging."],
  ["Sales from repeat purchases reduce dependence on costly new customer acquisition.", "Repeat sales lower acquisition reliance."],
  ["A marketing objective to double sales implies a substantial volume increase target.", "Doubling sales is an explicit volume ambition."],
  ["Sales growth supports the broader aim of making a profit after covering costs.", "Volume growth supports profit after cost coverage."],
  ["Trade promotions to retailers may aim to lift sell-through sales volume.", "Trade promos target sell-through volume."],
  ["Sales monitoring by region helps allocate marketing resources effectively.", "Regional sales data guides resource allocation."],
  ["Volume sold is a direct measure of progress on sales-related marketing objectives.", "Units sold directly measure sales progress."],
  ["Sales revenue must be earned before profit can be distributed or retained.", "Profit follows earned sales revenue."],
  ["A firm may accept lower margin temporarily to achieve a sales volume milestone.", "Volume milestones may justify temporary margin sacrifice."],
  ["Marketing objectives on sales recognise that businesses need revenues to operate.", "Sales objectives reflect revenue necessity."],
  ["Higher sales from satisfied loyal customers illustrate interrelated marketing objectives.", "Loyalty-driven sales show objective interrelation."],
  ["Sales targets for a new store opening reflect geographic expansion objectives.", "New store targets express geographic sales aims."],
  ["Volume growth without cost control may fail to improve profitability.", "Uncosted volume growth may not improve profit."],
  // Profitability (60)
  ["Profitability is a marketing objective because profits reimburse owners for invested money.", "Profits return value to owners for their investment."],
  ["Profits can be retained and reinvested in the business for future growth.", "Retained profits fund reinvestment."],
  ["Usually the higher the sales figures are, the more profit a business will make, with certain limitations.", "Higher sales generally raise profit subject to limitations."],
  ["Profitability objectives sit alongside satisfaction, differentiation, share, and sales goals.", "Profit is one objective among several."],
  ["Marketing success ultimately contributes to profit when revenues exceed relevant costs.", "Profit arises when revenue exceeds costs."],
  ["Owners expect profits as compensation for the capital they invested in the firm.", "Owner reimbursement is a stated profit rationale."],
  ["Retained profit can finance new equipment without raising external finance.", "Retained profit funds internal investment."],
  ["A profitability target may be expressed as a margin percentage on sales.", "Margin percentages operationalise profit targets."],
  ["Higher sales support profitability when unit margins and costs remain favourable.", "Favourable margins make higher sales support profit."],
  ["Profit objectives acknowledge that sales alone do not guarantee profit in every case.", "Limitations on the sales-profit link are recognised."],
  ["Marketing campaigns are assessed partly on whether they improve profitable sales.", "Campaigns should contribute to profitable sales."],
  ["Reinvestment of profit supports long-term marketing and production capacity.", "Reinvested profit builds future capacity."],
  ["Profitability is important because it sustains the business for owners and reinvestment.", "Profit sustains the business for owners and growth."],
  ["A firm may reject unprofitable volume that fails margin thresholds.", "Unprofitable volume may be rejected."],
  ["Cost increases can offset sales growth and limit profit improvement.", "Rising costs can cap profit despite sales growth."],
  ["Profit retained in the business reduces dependence on external borrowing for expansion.", "Retention lowers borrowing needs for expansion."],
  ["Marketing objectives include profitability because owners need returns on investment.", "Owner returns motivate profit objectives."],
  ["Discounting that raises sales volume may reduce profitability per unit sold.", "Discount-driven volume can cut unit profitability."],
  ["Profit measurement follows revenue from sales minus the costs of production and marketing.", "Profit is revenue minus relevant costs."],
  ["A profitability review examines whether marketing spend generated adequate returns.", "Marketing ROI forms part of profit review."],
  ["Satisfied loyal customers who buy repeatedly can improve lifetime profitability.", "Repeat loyal buyers can raise lifetime profit."],
  ["Profit reinvestment may fund brand-building that supports future differentiation.", "Profit can fund brand investment for USP."],
  ["Higher sales figures usually mean more profit, though limitations such as rising costs apply.", "The text notes the usual sales-profit link with limitations."],
  ["Profitability objectives encourage attention to cost coverage, not only gross revenue.", "Profit focus requires cost awareness beyond revenue."],
  ["Owners may withdraw part of profit as income while retaining the rest in the business.", "Profit can be distributed or retained."],
  ["A marketing plan should consider whether sales targets are profit-compatible.", "Targets should align with profit compatibility."],
  ["Profit from one product line can subsidise marketing investment in another line.", "Cross-line profit can fund marketing."],
  ["Profitability is linked to sales because sales provide the revenue base for profit calculation.", "Sales revenue forms the profit calculation base."],
  ["Retained earnings from profit strengthen the firm's internal finance for marketing.", "Retained profit supports marketing finance."],
  ["A firm pursuing share at the expense of margin may temporarily reduce profitability.", "Share pursuit can temporarily lower profit."],
  ["Profit objectives motivate efficient use of marketing budgets.", "Profit aims encourage marketing efficiency."],
  ["Limitations on the sales-profit link include unfavourable changes in unit costs.", "Unit cost changes limit the sales-profit relationship."],
  ["Profitability allows owners to be compensated while the firm retains funds for growth.", "Profit serves both owner compensation and retention."],
  ["Marketing staff may track gross profit by product to align with profitability objectives.", "Product-level gross profit tracks objective progress."],
  ["A USP supporting premium pricing can improve profitability if costs are controlled.", "Premium USP can lift profit with cost control."],
  ["Profit reinvestment in production capacity can support future sales growth.", "Capacity investment links profit retention to sales."],
  ["Profitability is a stated marketing objective in the textbook marketing overview.", "Profit is explicitly listed as a marketing objective."],
  ["Sales must cover production costs before any profit can be recorded.", "Cost coverage precedes profit recording."],
  ["Owners reinvest profit when they expect future returns from expanded operations.", "Reinvestment reflects expected future returns."],
  ["A decline in profitability despite stable sales may reflect higher input costs.", "Stable sales with falling profit may mean higher costs."],
  ["Profit targets may be set annually alongside sales and share objectives.", "Annual profit targets accompany other objectives."],
  ["Marketing that attracts profitable customer segments supports profitability objectives.", "Segment choice affects profit outcomes."],
  ["Retained profit is internally generated finance for marketing initiatives.", "Retention provides internal marketing finance."],
  ["The relationship between sales and profit is positive in general but not without exceptions.", "General positive link with exceptions is stated."],
  ["Profitability objectives remind managers that revenue growth must exceed cost growth.", "Profit requires revenue growth to beat cost growth."],
  ["A business may analyse contribution margin per unit to support profit objectives.", "Contribution margin analysis aids profit planning."],
  ["Profits reimburse owners and can be ploughed back into the business per the text.", "Owner reimbursement and reinvestment are both noted."],
  ["Marketing objectives on profit recognise limitations when discounting erodes margins.", "Discount erosion is a profit limitation."],
  ["Higher sales volume increases the revenue pool from which profit is calculated after costs.", "Larger revenue pool supports profit after costs."],
  ["Profit retention funds improvements that may later support customer satisfaction.", "Reinvestment can later improve satisfaction."],
  ["Profitability assessment includes whether marketing achieved cost-effective sales growth.", "Cost-effective growth matters for profit."],
  ["Owners' invested money is reimbursed through profits earned from successful operations.", "Operations generate profit that reimburses owners."],
  ["A firm may delay profit growth while investing heavily in brand and USP development.", "Brand investment may defer near-term profit."],
  ["Profit reinvestment is a strategic use of earnings kept within the business.", "Retained earnings serve strategic reinvestment."],
  ["Limitations on sales-driven profit include simultaneous increases in marketing expenditure.", "Higher marketing spend can limit profit from sales growth."],
  ["Profitability and sales objectives are interrelated but not identical measures.", "Sales and profit relate but differ."],
  ["Marketing performance should ultimately contribute to sustainable profitability.", "Sustainable profit is the long-run marketing contribution."],
  ["Retained profit strengthens the balance sheet for future marketing campaigns.", "Balance sheet strength supports future campaigns."],
  ["Profit per unit may fall even when total sales volume rises if prices are cut sharply.", "Sharp price cuts can reduce unit profit despite volume."],
  ["Profitability objectives align with owners' interest in returns on capital employed.", "Returns on capital align with profit aims."],
  ["A business analysing markets considers whether objectives will be profit-viable.", "Market analysis includes profit viability."],
  ["Marketing that builds loyalty can improve profitability through lower acquisition costs per sale.", "Loyalty lowers acquisition cost per sale."],
];

// --- FALSE statements (≥200 needed; 200 used) ---
const FALSE = [
  // Customer satisfaction traps (40)
  ["Customer satisfaction is unrelated to whether buyers purchase the product again.", "Satisfaction is explicitly interrelated with repeat purchase and loyalty objectives."],
  ["A dissatisfied customer may still become a loyal repeat buyer without any change in the product.", "Dissatisfied customers are unlikely to buy again per the marketing framework."],
  ["Customer satisfaction is the only marketing objective and replaces sales and profit goals.", "Satisfaction is one of several objectives, not the sole aim."],
  ["Businesses set marketing objectives without analysing customer wishes and needs.", "The text requires market and wishes/needs analysis before setting objectives."],
  ["Satisfied customers rarely buy the product again because loyalty is independent of satisfaction.", "Satisfied customers often become loyal and may buy again."],
  ["Customer satisfaction objectives apply only to service firms, not to goods producers.", "Satisfaction is a general marketing objective for businesses fulfilling customer needs."],
  ["Repeat purchase behaviour proves that customer satisfaction objectives are unnecessary.", "Repeat purchase is evidence satisfaction objectives matter, not that they are redundant."],
  ["Marketing objectives exclude customer satisfaction when profitability is prioritised.", "Profitability does not remove satisfaction from the set of possible objectives."],
  ["Dissatisfied customers will still buy again if the price is reduced slightly.", "The text states dissatisfied customers will not buy again, not merely resist until a small discount."],
  ["Customer satisfaction is measured only after profitability targets have been met.", "Satisfaction is an objective in its own right, not a post-profit afterthought."],
  ["Loyal customers emerge without any need for prior satisfaction with the product.", "Loyalty in the framework builds on satisfied customers who may buy again."],
  ["Customer satisfaction has no connection to market share or sales volume objectives.", "Satisfaction is interrelated with other marketing objectives including sales."],
  ["A business can ignore wishes and needs analysis if it already has a strong brand.", "Wishes and needs analysis precedes clear marketing objectives regardless of brand strength."],
  ["Satisfaction objectives mean customers must be delighted on every dimension or they will never return.", "The text requires satisfaction, not impossible perfection on every dimension."],
  ["Customer complaints rising after a campaign indicate success on satisfaction objectives.", "Rising complaints signal failure on satisfaction objectives."],
  ["Satisfied customers never recommend products to others, keeping satisfaction private.", "Satisfied customers may recommend products, extending marketing impact."],
  ["Customer satisfaction is achieved solely by lowering prices below competitors.", "Price cuts alone do not define satisfaction in the marketing objectives framework."],
  ["Once a customer buys once, satisfaction objectives are automatically fulfilled.", "A single purchase does not prove satisfaction objectives are met."],
  ["Dissatisfied customers continue buying out of habit, so satisfaction objectives are optional.", "Dissatisfied customers will not buy again according to the text."],
  ["Customer satisfaction objectives conflict with profitability and cannot coexist.", "Objectives are interrelated and can coexist within a marketing plan."],
  ["Satisfaction surveys are irrelevant to assessing marketing objective performance.", "Surveys help assess whether satisfaction objectives are being achieved."],
  ["A loyal customer is one who buys again regardless of whether they were satisfied.", "Loyalty is linked to satisfied customers who possibly buy again."],
  ["Customer satisfaction applies only after market share targets have been reached.", "Satisfaction is not deferred until share targets are met."],
  ["Marketing objectives treat satisfaction as separate from loyalty with no connection.", "Satisfaction and loyalty are explicitly linked in the framework."],
  ["Businesses need not fulfil wishes and needs if differentiation is strong enough.", "Fulfilling wishes and needs remains central even with differentiation."],
  ["Satisfied customers buy again only when legally required to do so under contract.", "Repeat purchase from satisfaction is voluntary customer behaviour."],
  ["Customer satisfaction is unrelated to sales because sales depend only on advertising spend.", "Satisfaction interrelates with sales through repeat purchase and loyalty."],
  ["A firm with high satisfaction can ignore market share because satisfied buyers guarantee success.", "Satisfaction supports but does not replace other objectives like share."],
  ["Dissatisfaction improves long-run sales by encouraging customers to try alternatives within the range.", "Dissatisfaction leads customers not to buy again, harming sales."],
  ["Customer satisfaction objectives are met when promotional reach is high, regardless of product experience.", "Reach alone does not satisfy; experience with the product matters."],
  ["Satisfied customers never buy complementary products from the same firm.", "Satisfied customers may buy other products from the firm."],
  ["Customer satisfaction is irrelevant to USP objectives because differentiation is purely visual.", "USP and satisfaction interrelate when customers experience the differentiated offer."],
  ["Repeat purchase rates falling while satisfaction scores rise always indicates data error only.", "Falling repurchase despite claimed satisfaction may reflect real objective failure."],
  ["Customer satisfaction means the product must be the cheapest in the market.", "Satisfaction concerns meeting wishes and needs, not being cheapest."],
  ["Loyalty programmes eliminate the need to pursue customer satisfaction objectives.", "Loyalty programmes complement but do not replace satisfaction objectives."],
  ["Dissatisfied customers still generate loyal behaviour if enrolled in a rewards scheme.", "Dissatisfaction undermines loyalty even with rewards enrolment."],
  ["Customer satisfaction is a financial accounting measure identical to gross profit.", "Satisfaction is a marketing objective distinct from gross profit."],
  ["Businesses set satisfaction objectives only in declining markets.", "Satisfaction is a general objective across market conditions."],
  ["A satisfied customer will never switch to a rival with a stronger USP.", "Satisfaction helps retention but does not make switching impossible."],
  ["Customer satisfaction objectives are fulfilled when production volume is maximised.", "Maximising production volume does not equate to customer satisfaction."],
  // USP / differentiation traps (40)
  ["A unique selling proposition means the product is identical to all similar products on every feature.", "USP means the product is or is considered different from similar products."],
  ["Product differentiation requires the product to be objectively unique in every technical respect.", "Differentiation can be based on perception and promotion as well as characteristics."],
  ["Building a brand has no role in creating a unique selling proposition.", "Building a brand supports creating a USP per the text."],
  ["A USP is achieved only when the firm holds one hundred percent market share.", "USP concerns differentiation, not total market dominance."],
  ["Product differentiation and unique selling proposition refer to unrelated marketing concepts.", "Differentiation is also called product differentiation in the USP context."],
  ["Promotion and customer perception cannot contribute to a product's unique selling proposition.", "Differentiation can arise from promotion and how customers perceive the product."],
  ["A USP means the product is worse than rivals but cheaper.", "USP positions the product as special, unique, or better than the rest."],
  ["Businesses avoid creating a USP because it attracts too many one-time buyers only.", "USP helps attract many loyal customers, not only one-time buyers."],
  ["Brand-building undermines differentiation by making all products appear the same.", "Brand-building supports rather than undermines USP creation."],
  ["A unique selling proposition eliminates the need for any customer satisfaction efforts.", "USP interrelates with satisfaction when customers experience the offer."],
  ["Differentiation objectives apply only to luxury goods and never to everyday products.", "USP and differentiation are general marketing objectives."],
  ["A USP based on promotion alone is not recognised as product differentiation.", "Promotion-based perception is explicitly valid for differentiation."],
  ["If two products share a brand, they cannot each have distinct unique selling propositions.", "Product lines may carry distinct USPs within a brand."],
  ["A product without a USP can still attract many loyal customers without any differentiation effort.", "USP aims to attract loyal customers through perceived difference."],
  ["Product differentiation means copying the market leader's features exactly.", "Differentiation requires difference from similar products, not exact copying."],
  ["A USP is defined solely by the lowest price in the product category.", "USP concerns uniqueness or perceived superiority, not price alone."],
  ["Building a brand is a financial objective unrelated to marketing differentiation.", "Brand-building supports USP within marketing objectives."],
  ["Customers cannot perceive a USP when products are functionally similar.", "Customers may consider a product different even when functional similarities exist."],
  ["A unique selling proposition guarantees unlimited market share without further effort.", "USP supports competitiveness but does not alone guarantee share."],
  ["Differentiation through packaging is excluded from the USP concept.", "Packaging and presentation can contribute to perceived differentiation."],
  ["A USP objective is met when the firm spends the most on advertising regardless of message.", "USP requires meaningful difference or perception, not spend alone."],
  ["Product differentiation replaces sales and profitability objectives entirely.", "Differentiation is one objective among several."],
  ["A USP must be based on a patented invention or it is invalid.", "USP can rest on characteristics or promotion, not only patents."],
  ["Brand loyalty and USP objectives are mutually exclusive marketing goals.", "Brand-building and USP work together to attract loyal customers."],
  ["A product considered the same as rivals still has a strong USP by definition.", "USP requires actual or perceived difference from similar products."],
  ["Differentiation means customers never compare the product with substitutes.", "Customers may still compare; USP shapes how the product is viewed in comparison."],
  ["A USP is created only when the product wins every industry quality award.", "Awards are not required; characteristics or perception can establish USP."],
  ["Promotion cannot change customer perception of uniqueness once the product is launched.", "Promotion shapes perception as a valid differentiation basis."],
  ["A unique selling proposition applies only to the promotion mix, not to the product.", "USP can rest on product characteristics or promotion and perception."],
  ["Businesses create USPs primarily to reduce sales volume by targeting fewer buyers.", "USP aims to attract many loyal customers, supporting sales."],
  ["Product differentiation is identical to market segmentation with no separate meaning.", "Differentiation concerns USP; segmentation is a distinct marketing concept."],
  ["A USP eliminates all price competition because differentiated products have fixed prices.", "USP reduces price-only competition but does not eliminate pricing decisions."],
  ["Brand-building is unnecessary when the product has a legally protected monopoly.", "Brand still supports perceived uniqueness even with limited competition."],
  ["A USP that emphasises speed of delivery cannot coexist with a quality-based USP.", "Different characteristics can be emphasised in USP messaging."],
  ["Differentiation objectives are unrelated to attracting loyal customers.", "USP is pursued because it helps attract many loyal customers."],
  ["A product that seems better than the rest cannot have a USP if rivals disagree.", "USP concerns customer perception, not unanimous rival agreement."],
  ["USP creation is a short-term tactic replaced by profitability objectives each quarter.", "USP is a sustained marketing objective, not a quarterly replacement for profit."],
  ["Product differentiation requires abandoning customer satisfaction objectives.", "Differentiation and satisfaction objectives interrelate."],
  ["A USP is valid only when verified by government regulators.", "USP rests on business positioning and customer perception, not regulatory certification."],
  ["Building a brand is the same as achieving maximum market share instantly.", "Brand-building supports USP; it does not instantly maximise share."],
  // Market share traps (40)
  ["Market share measures absolute sales volume with no reference to competitors.", "Market share indicates relative importance compared with competitors."],
  ["A firm with the highest absolute sales always has the highest market share in every market definition.", "Share depends on market boundary; highest absolute sales may not mean highest share."],
  ["Market share objectives are unrelated to competitiveness indicators.", "Market share is described as an indicator of competitiveness."],
  ["Gaining market share is impossible without simultaneously doubling production costs.", "Share can be gained through marketing without requiring cost doubling."],
  ["Market share is identical to customer satisfaction percentage in the marketing framework.", "Share and satisfaction are distinct objectives."],
  ["Businesses ignore competitors when setting market share objectives.", "Share is inherently relative to competitors' positions."],
  ["A declining market share always means absolute sales are falling.", "Share can fall while absolute sales rise if the market grows faster."],
  ["Market share is the only marketing objective that matters for public companies.", "Share is one of several possible marketing objectives."],
  ["Maintaining market share requires no marketing expenditure if the product once led.", "Share maintenance typically requires ongoing marketing effort."],
  ["Market share indicates a firm's absolute importance without comparing rivals.", "Share indicates relative importance compared with competitors."],
  ["A new entrant automatically receives fifty percent market share upon launch.", "Entrants must earn share through competitive performance."],
  ["Market share objectives replace profitability analysis entirely.", "Share complements but does not replace profit objectives."],
  ["Relative market importance is measured by total assets, not market share.", "Share, not assets alone, indicates relative market importance in this framework."],
  ["Gaining share always improves profitability in the same reporting period.", "Share gains may temporarily reduce profit when achieved through heavy spending."],
  ["Market share is calculated without defining which market boundary applies.", "Share requires a defined market among competing firms."],
  ["A firm can hold one hundred percent share in a market with no competitors by definition.", "Share comparisons require competitors within the defined market."],
  ["Market share maintenance is unrelated to customer loyalty programmes.", "Loyal customers help maintain share against rivals."],
  ["Share objectives are set without analysing the market the business operates in.", "Market analysis precedes objective setting including share targets."],
  ["Market share and sales volume objectives always move in opposite directions.", "Sales growth can support share when the firm outpaces market growth."],
  ["A competitiveness indicator excludes market share in favour of staff headcount alone.", "Share is explicitly a competitiveness indicator."],
  ["Losing share to a rival proves customer satisfaction objectives were exceeded.", "Share loss often signals competitive weakness, not excess satisfaction."],
  ["Market share is a marketing objective only for government agencies.", "Share objectives apply to businesses competing in markets."],
  ["Relative importance in the market is shown by advertising spend, not share.", "Share indicates relative importance; ad spend alone does not."],
  ["Gaining market share means the total market size must shrink.", "Share can be gained while the market grows or shrinks."],
  ["Market share objectives conflict with USP objectives and cannot be pursued together.", "Share and USP objectives can be pursued within one marketing plan."],
  ["A firm with zero market share still leads the market if its brand is well known.", "Leadership is reflected in share relative to competitors, not brand fame alone."],
  ["Market share is unchanged when a firm's sales double and all rivals' sales double.", "Equal proportional growth leaves share unchanged."],
  ["Maintaining share is unnecessary when absolute sales targets are met.", "Share adds relative competitiveness information beyond absolute sales."],
  ["Market share is measured in currency of production costs rather than sales.", "Share relates to portion of market sales, not production cost currency."],
  ["Competitiveness improves automatically when a firm reduces its market share.", "Share decline indicates weakened relative competitiveness."],
  ["Market share objectives apply only when the firm is the smallest competitor.", "Firms of any size may pursue share objectives."],
  ["A rising share always results from improved customer dissatisfaction among rivals' buyers.", "Share gains typically reflect competitive success, not rivals' dissatisfaction alone."],
  ["Market share is unrelated to sales because share excludes revenue entirely.", "Share derives from sales within the defined market."],
  ["Gaining share requires exiting the market temporarily.", "Share is gained by competing within the market."],
  ["Market share indicators are irrelevant when the firm sells only one product.", "Single-product firms still compete for share in their market."],
  ["Relative market position is assessed through share compared with competitors' positions.", "Share comparisons with rivals assess relative position."],
  ["Market share objectives mean the firm must acquire every competitor.", "Share objectives do not require acquiring all competitors."],
  ["A stable share in a growing market implies falling absolute sales.", "Stable share in a growing market can coincide with rising absolute sales."],
  ["Market share is a profitability measure identical to net margin.", "Share indicates relative sales position, not profit margin."],
  // Sales volume traps (40)
  ["Sales are unimportant to businesses because production costs are funded from share capital alone.", "Sales revenue is needed to cover production costs."],
  ["Maintaining or increasing sales is excluded from marketing objectives.", "Sales maintenance and growth are listed marketing objectives."],
  ["Revenue from sales is unnecessary for covering production costs if the brand is strong.", "Sales provide revenues that must cover production costs."],
  ["Higher sales always guarantee higher profit with no limitations whatsoever.", "The text notes limitations on the sales-profit relationship."],
  ["Sales objectives are met when promotional impressions reach a target audience count.", "Sales objectives concern units or revenue sold, not impressions alone."],
  ["A business can cover production costs without any sales if inventory is high.", "Costs are covered from sales revenue, not inventory holdings alone."],
  ["Increasing sales is unrelated to marketing objectives on profitability.", "Sales and profit objectives are interrelated."],
  ["Sales volume objectives apply only to firms that do not pursue market share.", "Sales and share objectives can coexist."],
  ["Revenue from sales exceeds production costs automatically at any positive unit price.", "Costs must be compared to revenue; low prices may fail to cover costs."],
  ["Marketing campaigns targeting awareness alone fulfil sales volume objectives without selling.", "Sales objectives require actual sales, not awareness alone."],
  ["Sales are important only to not-for-profit organisations, not to profit-seeking firms.", "Sales matter to businesses needing revenue to cover costs and profit."],
  ["Maintaining sales volume means keeping production output constant regardless of demand.", "Sales maintenance concerns customer purchases, not production output alone."],
  ["A decline in unit sales indicates success on sales growth objectives.", "Declining unit sales indicate failure on sales objectives."],
  ["Sales revenue and production costs are unrelated in the marketing framework.", "Sales revenue must cover production costs before profit."],
  ["Increasing sales requires reducing customer satisfaction to push quick transactions.", "Satisfaction supports sustainable sales; cutting satisfaction undermines repeat purchase."],
  ["Sales objectives are independent of market analysis of wishes and needs.", "Market analysis informs realistic sales objectives."],
  ["A firm with rising sales never needs to monitor production costs.", "Rising sales still require cost monitoring for profit objectives."],
  ["Sales volume objectives are achieved when warehouse stock levels peak.", "Stock levels do not equal sales to customers."],
  ["Revenue coverage of costs is irrelevant when pursuing differentiation objectives.", "Sales revenue remains necessary to cover costs alongside differentiation."],
  ["Sales growth from dissatisfied one-time buyers is a sustainable long-run strategy.", "Dissatisfied buyers will not sustain long-run sales through repeat purchase."],
  ["Unit sales targets are unrelated to quarterly marketing planning.", "Quarterly plans commonly include unit sales targets."],
  ["Sales are unconnected to profitability because profit comes only from asset sales.", "Profit in the framework comes from sales revenue minus costs."],
  ["Maintaining sales means prices must rise every month regardless of demand.", "Sales maintenance concerns volume sold, not mandatory monthly price rises."],
  ["A promotional campaign that raises awareness but not purchases meets sales objectives.", "Sales objectives require purchases generating revenue."],
  ["Sales volume is measured by the number of employees rather than customer purchases.", "Sales volume reflects customer purchases, not headcount."],
  ["Increasing sales is impossible when pursuing customer satisfaction objectives.", "Satisfaction supports repeat sales; the objectives interrelate."],
  ["Sales revenue cannot fund production costs if the product is differentiated.", "Differentiated products still require sales revenue to cover costs."],
  ["A business with zero sales can still meet sales volume objectives through forecasts.", "Objectives require actual sales performance, not forecasts alone."],
  ["Sales objectives replace the need for any profitability analysis.", "Sales support but do not replace profitability objectives."],
  ["Revenue from exports does not count toward sales volume objectives.", "Export sales contribute to total sales volume."],
  ["Higher sales figures always reduce production costs per unit to zero.", "Higher sales do not automatically eliminate unit costs."],
  ["Sales growth objectives are unrelated to customer loyalty from satisfaction.", "Loyal satisfied customers contribute to sales growth."],
  ["A temporary sales spike from a failed product satisfies long-term sales objectives.", "Failed products with unsatisfied buyers do not sustain long-term sales."],
  ["Sales are important because they allow the firm to ignore market share completely.", "Sales complement share objectives; they do not eliminate share relevance."],
  ["Maintaining sales requires shutting down marketing expenditure entirely.", "Sales maintenance typically requires continued marketing activity."],
  ["Sales volume and revenue are unrelated concepts in the marketing objectives framework.", "Revenue derives from volume and price together."],
  ["Production costs are covered from government grants rather than sales revenue.", "Sales revenue covers production costs in the standard business model described."],
  ["Increasing sales means profitability objectives become unnecessary.", "Profit remains a distinct objective even with rising sales."],
  ["Sales objectives are fulfilled when distribution centres are built, regardless of sell-through.", "Sell-through to customers defines sales achievement."],
  ["A firm can make a profit without any sales if customer satisfaction is high.", "Profit requires sales revenue exceeding costs; satisfaction alone does not replace sales."],
  // Profitability traps (40)
  ["Profitability is unrelated to sales because profits come only from borrowed funds.", "Profits arise from sales revenue relative to costs, not borrowing alone."],
  ["Higher sales always reduce profit because production costs rise infinitely with volume.", "Higher sales usually increase profit subject to limitations, not infinite cost rises."],
  ["Profits cannot be retained in the business for reinvestment under any circumstances.", "Profits can be retained and reinvested per the text."],
  ["Profitability objectives exclude owner reimbursement for invested capital.", "Profits reimburse owners for invested money."],
  ["Marketing objectives never include profitability because marketing only targets awareness.", "Profitability is listed among marketing objectives."],
  ["A firm with falling sales can always increase profit without any cost changes.", "Profit typically depends on sales and cost performance together."],
  ["Retained profit is identical to short-term trade credit from suppliers.", "Retained profit is internal equity from undistributed profit, not supplier credit."],
  ["Profitability and sales objectives are completely unrelated measures.", "Higher sales usually support profit with stated limitations."],
  ["Owners are reimbursed through sales volume alone without any profit calculation.", "Owners are reimbursed through profits, not unit volume alone."],
  ["Profit reinvestment is prohibited when a firm pursues USP objectives.", "Profit can be reinvested including in brand and differentiation."],
  ["There are no limitations on the link between higher sales and higher profit.", "The text explicitly notes certain limitations on the sales-profit link."],
  ["Profitability is achieved when market share reaches fifty percent regardless of costs.", "Profit requires revenue exceeding costs, not share alone."],
  ["Profits are unimportant because owners require no return on invested money.", "Profits are important to reimburse owners for invested capital."],
  ["A discounting strategy that maximises unit sales always maximises profit simultaneously.", "Discount-driven volume can reduce unit profitability."],
  ["Profitability objectives conflict with customer satisfaction and cannot coexist.", "Objectives interrelate and can coexist within marketing planning."],
  ["Retained earnings from profit cannot finance marketing campaigns.", "Retained profit can fund marketing and reinvestment."],
  ["Higher sales figures never contribute to profit under any market condition.", "Higher sales usually mean more profit with certain limitations."],
  ["Profit is recorded before sales revenue is earned from customers.", "Revenue from sales precedes profit calculation."],
  ["Marketing success is judged only by share gains with no regard to profit.", "Profitability is a recognised marketing objective alongside share."],
  ["Profit reinvestment means paying all revenue to suppliers immediately.", "Reinvestment retains profit in the business for future use."],
  ["Profitability requires sales to fall so that costs can be eliminated.", "Profit generally benefits from adequate sales covering costs."],
  ["Owners' invested money is reimbursed through promotional reach metrics.", "Owners are reimbursed through profits, not reach metrics."],
  ["A USP guarantees profit without regard to sales volume or costs.", "USP supports marketing but profit still depends on sales and costs."],
  ["Profitability objectives apply only when the firm has no competitors.", "Profit objectives apply in competitive markets."],
  ["Retained profit must be distributed entirely to creditors each year.", "Profit can be retained in the business rather than paid to creditors."],
  ["Limitations on the sales-profit link mean higher sales always lower profit.", "Limitations qualify the positive link; they do not reverse it always."],
  ["Profitability is unrelated to marketing because marketing generates only costs.", "Marketing aims contribute to profitable sales outcomes."],
  ["A firm with high customer satisfaction cannot pursue profitability objectives.", "Satisfaction and profitability objectives can be pursued together."],
  ["Profit reinvestment is the same as issuing new share capital to investors.", "Reinvestment uses retained profit internally, unlike new share issues."],
  ["Sales covering production costs is sufficient for profit with no margin required.", "Profit requires revenue above costs, not mere cost coverage alone."],
  ["Profitability is measured by customer satisfaction scores rather than financial surplus.", "Profit is a financial surplus; satisfaction is a separate objective."],
  ["Higher sales always eliminate the need to reinvest profit in the business.", "Reinvestment remains valuable even when sales rise."],
  ["Profit objectives are met when advertising spending equals total revenue.", "Matching ad spend to revenue does not define profit."],
  ["Owners receive reimbursement only through wages, never through profit.", "Profits reimburse owners for invested money per the text."],
  ["Profitability and market share move in opposite directions in every case.", "Share and profit can both improve or require trade-offs depending on strategy."],
  ["Retained profit cannot support production capacity expansion.", "Retained profit can be reinvested in the business including capacity."],
  ["A profitability objective is fulfilled when the firm has the most employees.", "Profit relates to financial surplus, not headcount."],
  ["Marketing that raises sales with rising costs always increases profit.", "Rising costs can offset sales growth and limit profit gains."],
  ["Profitability is excluded when businesses analyse customer wishes and needs.", "Profit is one objective set alongside market analysis."],
  ["Profits are important only for tax purposes and not for reinvestment.", "Profits can be retained and reinvested in the business."],
  ["Marketing objectives exclude profitability whenever sales volume targets are set.", "Profitability remains a valid objective alongside sales volume targets."],
];

if (TRUE.length < 300) throw new Error(`TRUE pool ${TRUE.length} < 300`);
if (FALSE.length < 200) throw new Error(`FALSE pool ${FALSE.length} < 200`);

const cases = buildCases({
  subsection: "5.2",
  slots,
  TRUE,
  FALSE,
  SCENE,
  THEORY,
  TITLES,
  sceneIndices,
});

validateAndWrite(cases, slots, OUT);
