/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as MockExamsRouteImport } from './routes/mock-exams'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportantFeaturesRouteImport } from './routes/important-features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as DemoPracticeRouteImport } from './routes/demo-practice'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as MockExamsIndexRouteImport } from './routes/mock-exams.index'
import { Route as FlashcardsIndexRouteImport } from './routes/flashcards.index'
import { Route as DemoPracticeIndexRouteImport } from './routes/demo-practice.index'
import { Route as ProductsLiteBbeCourseSubjectsRouteImport } from './routes/products.lite-bbe-course-subjects'
import { Route as ProductsLiteBbeCourseMathRouteImport } from './routes/products.lite-bbe-course-math'
import { Route as ProductsLiteBbeCourseEnglishRouteImport } from './routes/products.lite-bbe-course-english'
import { Route as ProductsLiteBbeCourseRouteImport } from './routes/products.lite-bbe-course'
import { Route as ProductsFullCourseSubjectsRouteImport } from './routes/products.full-course-subjects'
import { Route as ProductsFullCourseMathRouteImport } from './routes/products.full-course-math'
import { Route as ProductsFullCourseEnglishRouteImport } from './routes/products.full-course-english'
import { Route as ProductsFullCourseEconomicsRouteImport } from './routes/products.full-course-economics'
import { Route as ProductsFullCourseRouteImport } from './routes/products.full-course'
import { Route as ProductsDemoPracticeRouteImport } from './routes/products.demo-practice'
import { Route as ProductsCustomMockBuilderRouteImport } from './routes/products.custom-mock-builder'
import { Route as FlashcardsSubjectRouteImport } from './routes/flashcards.$subject'
import { Route as FeaturesAnswerSheetRouteImport } from './routes/features.answer-sheet'
import { Route as DemoPracticeMathRouteImport } from './routes/demo-practice.math'
import { Route as DemoPracticeEnglishRouteImport } from './routes/demo-practice.english'
import { Route as DemoPracticeEconomicsRouteImport } from './routes/demo-practice.economics'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminEconomicsRouteImport } from './routes/admin.economics'
import { Route as MockExamsExamIdTakeRouteImport } from './routes/mock-exams.$examId.take'
import { Route as MockExamsExamIdReviewRouteImport } from './routes/mock-exams.$examId.review'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const MockExamsRoute = MockExamsRouteImport.update({
  id: '/mock-exams',
  path: '/mock-exams',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportantFeaturesRoute = ImportantFeaturesRouteImport.update({
  id: '/important-features',
  path: '/important-features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPracticeRoute = DemoPracticeRouteImport.update({
  id: '/demo-practice',
  path: '/demo-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const MockExamsIndexRoute = MockExamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MockExamsRoute,
} as any)
const FlashcardsIndexRoute = FlashcardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FlashcardsRoute,
} as any)
const DemoPracticeIndexRoute = DemoPracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoPracticeRoute,
} as any)
const ProductsLiteBbeCourseSubjectsRoute =
  ProductsLiteBbeCourseSubjectsRouteImport.update({
    id: '/lite-bbe-course-subjects',
    path: '/lite-bbe-course-subjects',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsLiteBbeCourseMathRoute =
  ProductsLiteBbeCourseMathRouteImport.update({
    id: '/lite-bbe-course-math',
    path: '/lite-bbe-course-math',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsLiteBbeCourseEnglishRoute =
  ProductsLiteBbeCourseEnglishRouteImport.update({
    id: '/lite-bbe-course-english',
    path: '/lite-bbe-course-english',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsLiteBbeCourseRoute = ProductsLiteBbeCourseRouteImport.update({
  id: '/lite-bbe-course',
  path: '/lite-bbe-course',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsFullCourseSubjectsRoute =
  ProductsFullCourseSubjectsRouteImport.update({
    id: '/full-course-subjects',
    path: '/full-course-subjects',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsFullCourseMathRoute = ProductsFullCourseMathRouteImport.update({
  id: '/full-course-math',
  path: '/full-course-math',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsFullCourseEnglishRoute =
  ProductsFullCourseEnglishRouteImport.update({
    id: '/full-course-english',
    path: '/full-course-english',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsFullCourseEconomicsRoute =
  ProductsFullCourseEconomicsRouteImport.update({
    id: '/full-course-economics',
    path: '/full-course-economics',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsFullCourseRoute = ProductsFullCourseRouteImport.update({
  id: '/full-course',
  path: '/full-course',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsDemoPracticeRoute = ProductsDemoPracticeRouteImport.update({
  id: '/demo-practice',
  path: '/demo-practice',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCustomMockBuilderRoute =
  ProductsCustomMockBuilderRouteImport.update({
    id: '/custom-mock-builder',
    path: '/custom-mock-builder',
    getParentRoute: () => ProductsRoute,
  } as any)
const FlashcardsSubjectRoute = FlashcardsSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => FlashcardsRoute,
} as any)
const FeaturesAnswerSheetRoute = FeaturesAnswerSheetRouteImport.update({
  id: '/features/answer-sheet',
  path: '/features/answer-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPracticeMathRoute = DemoPracticeMathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => DemoPracticeRoute,
} as any)
const DemoPracticeEnglishRoute = DemoPracticeEnglishRouteImport.update({
  id: '/english',
  path: '/english',
  getParentRoute: () => DemoPracticeRoute,
} as any)
const DemoPracticeEconomicsRoute = DemoPracticeEconomicsRouteImport.update({
  id: '/economics',
  path: '/economics',
  getParentRoute: () => DemoPracticeRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEconomicsRoute = AdminEconomicsRouteImport.update({
  id: '/economics',
  path: '/economics',
  getParentRoute: () => AdminRoute,
} as any)
const MockExamsExamIdTakeRoute = MockExamsExamIdTakeRouteImport.update({
  id: '/$examId/take',
  path: '/$examId/take',
  getParentRoute: () => MockExamsRoute,
} as any)
const MockExamsExamIdReviewRoute = MockExamsExamIdReviewRouteImport.update({
  id: '/$examId/review',
  path: '/$examId/review',
  getParentRoute: () => MockExamsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/demo-practice': typeof DemoPracticeRouteWithChildren
  '/flashcards': typeof FlashcardsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/important-features': typeof ImportantFeaturesRoute
  '/login': typeof LoginRoute
  '/mock-exams': typeof MockExamsRouteWithChildren
  '/parents': typeof ParentsRoute
  '/practice': typeof PracticeRoute
  '/products': typeof ProductsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/economics': typeof AdminEconomicsRoute
  '/api/chat': typeof ApiChatRoute
  '/demo-practice/economics': typeof DemoPracticeEconomicsRoute
  '/demo-practice/english': typeof DemoPracticeEnglishRoute
  '/demo-practice/math': typeof DemoPracticeMathRoute
  '/features/answer-sheet': typeof FeaturesAnswerSheetRoute
  '/flashcards/$subject': typeof FlashcardsSubjectRoute
  '/products/custom-mock-builder': typeof ProductsCustomMockBuilderRoute
  '/products/demo-practice': typeof ProductsDemoPracticeRoute
  '/products/full-course': typeof ProductsFullCourseRoute
  '/products/full-course-economics': typeof ProductsFullCourseEconomicsRoute
  '/products/full-course-english': typeof ProductsFullCourseEnglishRoute
  '/products/full-course-math': typeof ProductsFullCourseMathRoute
  '/products/full-course-subjects': typeof ProductsFullCourseSubjectsRoute
  '/products/lite-bbe-course': typeof ProductsLiteBbeCourseRoute
  '/products/lite-bbe-course-english': typeof ProductsLiteBbeCourseEnglishRoute
  '/products/lite-bbe-course-math': typeof ProductsLiteBbeCourseMathRoute
  '/products/lite-bbe-course-subjects': typeof ProductsLiteBbeCourseSubjectsRoute
  '/demo-practice/': typeof DemoPracticeIndexRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/mock-exams/': typeof MockExamsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/mock-exams/$examId/review': typeof MockExamsExamIdReviewRoute
  '/mock-exams/$examId/take': typeof MockExamsExamIdTakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/important-features': typeof ImportantFeaturesRoute
  '/login': typeof LoginRoute
  '/parents': typeof ParentsRoute
  '/practice': typeof PracticeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/economics': typeof AdminEconomicsRoute
  '/api/chat': typeof ApiChatRoute
  '/demo-practice/economics': typeof DemoPracticeEconomicsRoute
  '/demo-practice/english': typeof DemoPracticeEnglishRoute
  '/demo-practice/math': typeof DemoPracticeMathRoute
  '/features/answer-sheet': typeof FeaturesAnswerSheetRoute
  '/flashcards/$subject': typeof FlashcardsSubjectRoute
  '/products/custom-mock-builder': typeof ProductsCustomMockBuilderRoute
  '/products/demo-practice': typeof ProductsDemoPracticeRoute
  '/products/full-course': typeof ProductsFullCourseRoute
  '/products/full-course-economics': typeof ProductsFullCourseEconomicsRoute
  '/products/full-course-english': typeof ProductsFullCourseEnglishRoute
  '/products/full-course-math': typeof ProductsFullCourseMathRoute
  '/products/full-course-subjects': typeof ProductsFullCourseSubjectsRoute
  '/products/lite-bbe-course': typeof ProductsLiteBbeCourseRoute
  '/products/lite-bbe-course-english': typeof ProductsLiteBbeCourseEnglishRoute
  '/products/lite-bbe-course-math': typeof ProductsLiteBbeCourseMathRoute
  '/products/lite-bbe-course-subjects': typeof ProductsLiteBbeCourseSubjectsRoute
  '/demo-practice': typeof DemoPracticeIndexRoute
  '/flashcards': typeof FlashcardsIndexRoute
  '/mock-exams': typeof MockExamsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/mock-exams/$examId/review': typeof MockExamsExamIdReviewRoute
  '/mock-exams/$examId/take': typeof MockExamsExamIdTakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/demo-practice': typeof DemoPracticeRouteWithChildren
  '/flashcards': typeof FlashcardsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/important-features': typeof ImportantFeaturesRoute
  '/login': typeof LoginRoute
  '/mock-exams': typeof MockExamsRouteWithChildren
  '/parents': typeof ParentsRoute
  '/practice': typeof PracticeRoute
  '/products': typeof ProductsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/economics': typeof AdminEconomicsRoute
  '/api/chat': typeof ApiChatRoute
  '/demo-practice/economics': typeof DemoPracticeEconomicsRoute
  '/demo-practice/english': typeof DemoPracticeEnglishRoute
  '/demo-practice/math': typeof DemoPracticeMathRoute
  '/features/answer-sheet': typeof FeaturesAnswerSheetRoute
  '/flashcards/$subject': typeof FlashcardsSubjectRoute
  '/products/custom-mock-builder': typeof ProductsCustomMockBuilderRoute
  '/products/demo-practice': typeof ProductsDemoPracticeRoute
  '/products/full-course': typeof ProductsFullCourseRoute
  '/products/full-course-economics': typeof ProductsFullCourseEconomicsRoute
  '/products/full-course-english': typeof ProductsFullCourseEnglishRoute
  '/products/full-course-math': typeof ProductsFullCourseMathRoute
  '/products/full-course-subjects': typeof ProductsFullCourseSubjectsRoute
  '/products/lite-bbe-course': typeof ProductsLiteBbeCourseRoute
  '/products/lite-bbe-course-english': typeof ProductsLiteBbeCourseEnglishRoute
  '/products/lite-bbe-course-math': typeof ProductsLiteBbeCourseMathRoute
  '/products/lite-bbe-course-subjects': typeof ProductsLiteBbeCourseSubjectsRoute
  '/demo-practice/': typeof DemoPracticeIndexRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/mock-exams/': typeof MockExamsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/mock-exams/$examId/review': typeof MockExamsExamIdReviewRoute
  '/mock-exams/$examId/take': typeof MockExamsExamIdTakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/demo-practice'
    | '/flashcards'
    | '/forgot-password'
    | '/important-features'
    | '/login'
    | '/mock-exams'
    | '/parents'
    | '/practice'
    | '/products'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin/economics'
    | '/api/chat'
    | '/demo-practice/economics'
    | '/demo-practice/english'
    | '/demo-practice/math'
    | '/features/answer-sheet'
    | '/flashcards/$subject'
    | '/products/custom-mock-builder'
    | '/products/demo-practice'
    | '/products/full-course'
    | '/products/full-course-economics'
    | '/products/full-course-english'
    | '/products/full-course-math'
    | '/products/full-course-subjects'
    | '/products/lite-bbe-course'
    | '/products/lite-bbe-course-english'
    | '/products/lite-bbe-course-math'
    | '/products/lite-bbe-course-subjects'
    | '/demo-practice/'
    | '/flashcards/'
    | '/mock-exams/'
    | '/products/'
    | '/mock-exams/$examId/review'
    | '/mock-exams/$examId/take'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/important-features'
    | '/login'
    | '/parents'
    | '/practice'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin/economics'
    | '/api/chat'
    | '/demo-practice/economics'
    | '/demo-practice/english'
    | '/demo-practice/math'
    | '/features/answer-sheet'
    | '/flashcards/$subject'
    | '/products/custom-mock-builder'
    | '/products/demo-practice'
    | '/products/full-course'
    | '/products/full-course-economics'
    | '/products/full-course-english'
    | '/products/full-course-math'
    | '/products/full-course-subjects'
    | '/products/lite-bbe-course'
    | '/products/lite-bbe-course-english'
    | '/products/lite-bbe-course-math'
    | '/products/lite-bbe-course-subjects'
    | '/demo-practice'
    | '/flashcards'
    | '/mock-exams'
    | '/products'
    | '/mock-exams/$examId/review'
    | '/mock-exams/$examId/take'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/demo-practice'
    | '/flashcards'
    | '/forgot-password'
    | '/important-features'
    | '/login'
    | '/mock-exams'
    | '/parents'
    | '/practice'
    | '/products'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin/economics'
    | '/api/chat'
    | '/demo-practice/economics'
    | '/demo-practice/english'
    | '/demo-practice/math'
    | '/features/answer-sheet'
    | '/flashcards/$subject'
    | '/products/custom-mock-builder'
    | '/products/demo-practice'
    | '/products/full-course'
    | '/products/full-course-economics'
    | '/products/full-course-english'
    | '/products/full-course-math'
    | '/products/full-course-subjects'
    | '/products/lite-bbe-course'
    | '/products/lite-bbe-course-english'
    | '/products/lite-bbe-course-math'
    | '/products/lite-bbe-course-subjects'
    | '/demo-practice/'
    | '/flashcards/'
    | '/mock-exams/'
    | '/products/'
    | '/mock-exams/$examId/review'
    | '/mock-exams/$examId/take'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DemoPracticeRoute: typeof DemoPracticeRouteWithChildren
  FlashcardsRoute: typeof FlashcardsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImportantFeaturesRoute: typeof ImportantFeaturesRoute
  LoginRoute: typeof LoginRoute
  MockExamsRoute: typeof MockExamsRouteWithChildren
  ParentsRoute: typeof ParentsRoute
  PracticeRoute: typeof PracticeRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  FeaturesAnswerSheetRoute: typeof FeaturesAnswerSheetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-exams': {
      id: '/mock-exams'
      path: '/mock-exams'
      fullPath: '/mock-exams'
      preLoaderRoute: typeof MockExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/important-features': {
      id: '/important-features'
      path: '/important-features'
      fullPath: '/important-features'
      preLoaderRoute: typeof ImportantFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-practice': {
      id: '/demo-practice'
      path: '/demo-practice'
      fullPath: '/demo-practice'
      preLoaderRoute: typeof DemoPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/mock-exams/': {
      id: '/mock-exams/'
      path: '/'
      fullPath: '/mock-exams/'
      preLoaderRoute: typeof MockExamsIndexRouteImport
      parentRoute: typeof MockExamsRoute
    }
    '/flashcards/': {
      id: '/flashcards/'
      path: '/'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof FlashcardsIndexRouteImport
      parentRoute: typeof FlashcardsRoute
    }
    '/demo-practice/': {
      id: '/demo-practice/'
      path: '/'
      fullPath: '/demo-practice/'
      preLoaderRoute: typeof DemoPracticeIndexRouteImport
      parentRoute: typeof DemoPracticeRoute
    }
    '/products/lite-bbe-course-subjects': {
      id: '/products/lite-bbe-course-subjects'
      path: '/lite-bbe-course-subjects'
      fullPath: '/products/lite-bbe-course-subjects'
      preLoaderRoute: typeof ProductsLiteBbeCourseSubjectsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/lite-bbe-course-math': {
      id: '/products/lite-bbe-course-math'
      path: '/lite-bbe-course-math'
      fullPath: '/products/lite-bbe-course-math'
      preLoaderRoute: typeof ProductsLiteBbeCourseMathRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/lite-bbe-course-english': {
      id: '/products/lite-bbe-course-english'
      path: '/lite-bbe-course-english'
      fullPath: '/products/lite-bbe-course-english'
      preLoaderRoute: typeof ProductsLiteBbeCourseEnglishRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/lite-bbe-course': {
      id: '/products/lite-bbe-course'
      path: '/lite-bbe-course'
      fullPath: '/products/lite-bbe-course'
      preLoaderRoute: typeof ProductsLiteBbeCourseRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/full-course-subjects': {
      id: '/products/full-course-subjects'
      path: '/full-course-subjects'
      fullPath: '/products/full-course-subjects'
      preLoaderRoute: typeof ProductsFullCourseSubjectsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/full-course-math': {
      id: '/products/full-course-math'
      path: '/full-course-math'
      fullPath: '/products/full-course-math'
      preLoaderRoute: typeof ProductsFullCourseMathRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/full-course-english': {
      id: '/products/full-course-english'
      path: '/full-course-english'
      fullPath: '/products/full-course-english'
      preLoaderRoute: typeof ProductsFullCourseEnglishRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/full-course-economics': {
      id: '/products/full-course-economics'
      path: '/full-course-economics'
      fullPath: '/products/full-course-economics'
      preLoaderRoute: typeof ProductsFullCourseEconomicsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/full-course': {
      id: '/products/full-course'
      path: '/full-course'
      fullPath: '/products/full-course'
      preLoaderRoute: typeof ProductsFullCourseRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/demo-practice': {
      id: '/products/demo-practice'
      path: '/demo-practice'
      fullPath: '/products/demo-practice'
      preLoaderRoute: typeof ProductsDemoPracticeRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/custom-mock-builder': {
      id: '/products/custom-mock-builder'
      path: '/custom-mock-builder'
      fullPath: '/products/custom-mock-builder'
      preLoaderRoute: typeof ProductsCustomMockBuilderRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/flashcards/$subject': {
      id: '/flashcards/$subject'
      path: '/$subject'
      fullPath: '/flashcards/$subject'
      preLoaderRoute: typeof FlashcardsSubjectRouteImport
      parentRoute: typeof FlashcardsRoute
    }
    '/features/answer-sheet': {
      id: '/features/answer-sheet'
      path: '/features/answer-sheet'
      fullPath: '/features/answer-sheet'
      preLoaderRoute: typeof FeaturesAnswerSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-practice/math': {
      id: '/demo-practice/math'
      path: '/math'
      fullPath: '/demo-practice/math'
      preLoaderRoute: typeof DemoPracticeMathRouteImport
      parentRoute: typeof DemoPracticeRoute
    }
    '/demo-practice/english': {
      id: '/demo-practice/english'
      path: '/english'
      fullPath: '/demo-practice/english'
      preLoaderRoute: typeof DemoPracticeEnglishRouteImport
      parentRoute: typeof DemoPracticeRoute
    }
    '/demo-practice/economics': {
      id: '/demo-practice/economics'
      path: '/economics'
      fullPath: '/demo-practice/economics'
      preLoaderRoute: typeof DemoPracticeEconomicsRouteImport
      parentRoute: typeof DemoPracticeRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/economics': {
      id: '/admin/economics'
      path: '/economics'
      fullPath: '/admin/economics'
      preLoaderRoute: typeof AdminEconomicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mock-exams/$examId/take': {
      id: '/mock-exams/$examId/take'
      path: '/$examId/take'
      fullPath: '/mock-exams/$examId/take'
      preLoaderRoute: typeof MockExamsExamIdTakeRouteImport
      parentRoute: typeof MockExamsRoute
    }
    '/mock-exams/$examId/review': {
      id: '/mock-exams/$examId/review'
      path: '/$examId/review'
      fullPath: '/mock-exams/$examId/review'
      preLoaderRoute: typeof MockExamsExamIdReviewRouteImport
      parentRoute: typeof MockExamsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEconomicsRoute: typeof AdminEconomicsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEconomicsRoute: AdminEconomicsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DemoPracticeRouteChildren {
  DemoPracticeEconomicsRoute: typeof DemoPracticeEconomicsRoute
  DemoPracticeEnglishRoute: typeof DemoPracticeEnglishRoute
  DemoPracticeMathRoute: typeof DemoPracticeMathRoute
  DemoPracticeIndexRoute: typeof DemoPracticeIndexRoute
}

const DemoPracticeRouteChildren: DemoPracticeRouteChildren = {
  DemoPracticeEconomicsRoute: DemoPracticeEconomicsRoute,
  DemoPracticeEnglishRoute: DemoPracticeEnglishRoute,
  DemoPracticeMathRoute: DemoPracticeMathRoute,
  DemoPracticeIndexRoute: DemoPracticeIndexRoute,
}

const DemoPracticeRouteWithChildren = DemoPracticeRoute._addFileChildren(
  DemoPracticeRouteChildren,
)

interface FlashcardsRouteChildren {
  FlashcardsSubjectRoute: typeof FlashcardsSubjectRoute
  FlashcardsIndexRoute: typeof FlashcardsIndexRoute
}

const FlashcardsRouteChildren: FlashcardsRouteChildren = {
  FlashcardsSubjectRoute: FlashcardsSubjectRoute,
  FlashcardsIndexRoute: FlashcardsIndexRoute,
}

const FlashcardsRouteWithChildren = FlashcardsRoute._addFileChildren(
  FlashcardsRouteChildren,
)

interface MockExamsRouteChildren {
  MockExamsIndexRoute: typeof MockExamsIndexRoute
  MockExamsExamIdReviewRoute: typeof MockExamsExamIdReviewRoute
  MockExamsExamIdTakeRoute: typeof MockExamsExamIdTakeRoute
}

const MockExamsRouteChildren: MockExamsRouteChildren = {
  MockExamsIndexRoute: MockExamsIndexRoute,
  MockExamsExamIdReviewRoute: MockExamsExamIdReviewRoute,
  MockExamsExamIdTakeRoute: MockExamsExamIdTakeRoute,
}

const MockExamsRouteWithChildren = MockExamsRoute._addFileChildren(
  MockExamsRouteChildren,
)

interface ProductsRouteChildren {
  ProductsCustomMockBuilderRoute: typeof ProductsCustomMockBuilderRoute
  ProductsDemoPracticeRoute: typeof ProductsDemoPracticeRoute
  ProductsFullCourseRoute: typeof ProductsFullCourseRoute
  ProductsFullCourseEconomicsRoute: typeof ProductsFullCourseEconomicsRoute
  ProductsFullCourseEnglishRoute: typeof ProductsFullCourseEnglishRoute
  ProductsFullCourseMathRoute: typeof ProductsFullCourseMathRoute
  ProductsFullCourseSubjectsRoute: typeof ProductsFullCourseSubjectsRoute
  ProductsLiteBbeCourseRoute: typeof ProductsLiteBbeCourseRoute
  ProductsLiteBbeCourseEnglishRoute: typeof ProductsLiteBbeCourseEnglishRoute
  ProductsLiteBbeCourseMathRoute: typeof ProductsLiteBbeCourseMathRoute
  ProductsLiteBbeCourseSubjectsRoute: typeof ProductsLiteBbeCourseSubjectsRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsCustomMockBuilderRoute: ProductsCustomMockBuilderRoute,
  ProductsDemoPracticeRoute: ProductsDemoPracticeRoute,
  ProductsFullCourseRoute: ProductsFullCourseRoute,
  ProductsFullCourseEconomicsRoute: ProductsFullCourseEconomicsRoute,
  ProductsFullCourseEnglishRoute: ProductsFullCourseEnglishRoute,
  ProductsFullCourseMathRoute: ProductsFullCourseMathRoute,
  ProductsFullCourseSubjectsRoute: ProductsFullCourseSubjectsRoute,
  ProductsLiteBbeCourseRoute: ProductsLiteBbeCourseRoute,
  ProductsLiteBbeCourseEnglishRoute: ProductsLiteBbeCourseEnglishRoute,
  ProductsLiteBbeCourseMathRoute: ProductsLiteBbeCourseMathRoute,
  ProductsLiteBbeCourseSubjectsRoute: ProductsLiteBbeCourseSubjectsRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DemoPracticeRoute: DemoPracticeRouteWithChildren,
  FlashcardsRoute: FlashcardsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImportantFeaturesRoute: ImportantFeaturesRoute,
  LoginRoute: LoginRoute,
  MockExamsRoute: MockExamsRouteWithChildren,
  ParentsRoute: ParentsRoute,
  PracticeRoute: PracticeRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  FeaturesAnswerSheetRoute: FeaturesAnswerSheetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
