/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoPracticeRouteImport } from './routes/demo-practice'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoPracticeEconomicsRouteImport } from './routes/demo-practice.economics'
import { Route as AdminEconomicsRouteImport } from './routes/admin.economics'

const DemoPracticeRoute = DemoPracticeRouteImport.update({
  id: '/demo-practice',
  path: '/demo-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPracticeEconomicsRoute = DemoPracticeEconomicsRouteImport.update({
  id: '/economics',
  path: '/economics',
  getParentRoute: () => DemoPracticeRoute,
} as any)
const AdminEconomicsRoute = AdminEconomicsRouteImport.update({
  id: '/admin/economics',
  path: '/admin/economics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo-practice': typeof DemoPracticeRouteWithChildren
  '/admin/economics': typeof AdminEconomicsRoute
  '/demo-practice/economics': typeof DemoPracticeEconomicsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo-practice': typeof DemoPracticeRouteWithChildren
  '/admin/economics': typeof AdminEconomicsRoute
  '/demo-practice/economics': typeof DemoPracticeEconomicsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo-practice': typeof DemoPracticeRouteWithChildren
  '/admin/economics': typeof AdminEconomicsRoute
  '/demo-practice/economics': typeof DemoPracticeEconomicsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo-practice'
    | '/admin/economics'
    | '/demo-practice/economics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo-practice'
    | '/admin/economics'
    | '/demo-practice/economics'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/demo-practice'
    | '/admin/economics'
    | '/demo-practice/economics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DemoPracticeRoute: typeof DemoPracticeRouteWithChildren
  AdminEconomicsRoute: typeof AdminEconomicsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo-practice': {
      id: '/demo-practice'
      path: '/demo-practice'
      fullPath: '/demo-practice'
      preLoaderRoute: typeof DemoPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-practice/economics': {
      id: '/demo-practice/economics'
      path: '/economics'
      fullPath: '/demo-practice/economics'
      preLoaderRoute: typeof DemoPracticeEconomicsRouteImport
      parentRoute: typeof DemoPracticeRoute
    }
    '/admin/economics': {
      id: '/admin/economics'
      path: '/admin/economics'
      fullPath: '/admin/economics'
      preLoaderRoute: typeof AdminEconomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DemoPracticeRouteChildren {
  DemoPracticeEconomicsRoute: typeof DemoPracticeEconomicsRoute
}

const DemoPracticeRouteChildren: DemoPracticeRouteChildren = {
  DemoPracticeEconomicsRoute: DemoPracticeEconomicsRoute,
}

const DemoPracticeRouteWithChildren = DemoPracticeRoute._addFileChildren(
  DemoPracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DemoPracticeRoute: DemoPracticeRouteWithChildren,
  AdminEconomicsRoute: AdminEconomicsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
