/**
 * Chapter 9 — Polynomial functions (no book subtopics).
 * Fifty cases, ten at each difficulty from 1/5 to 5/5. Twelve stems are purely
 * symbolic (structure only, no coefficients), ten carry an SVG plot generated
 * from the polynomial the statements discuss, and the rest are formula,
 * applied, table, parametric or hybrid stems. MATH 9.01 is the photo exemplar
 * at 3/5: a cubic velocity model on one train line plus a distance log on
 * another.
 * Explanations follow the Chapter 4 tutor voice (narrative opener, one
 * single-line display per step, verdict woven into the last sentence).
 * Generated by scripts/gen-ch9-polynomials.py — edit the generator, not this.
 */

import type { MathTask } from "@/data/math-chapters";
import ch9 from "@/data/math-ch9-polynomials.json";

/** Flat chapter bank — practice UI has no subsection chrome for chapter 9. */
export const MATH_CH9_POLYNOMIALS: MathTask[] = (ch9.tasks as MathTask[]).map((task, i) => ({
  ...task,
  subsection: task.subsection ?? "9",
  sort_order: task.sort_order ?? i + 1,
  placeholder: false,
}));
