/**
 * Chapter 4 — Subsection 4.4: Exponential and logarithmic equations.
 * Generated by scripts/generate-math-ch4-exam.mjs
 */

import type { MathTask } from "@/data/math-chapters";

export const MATH_CH4_4_EXPONENTIAL: MathTask[] = [
  {
    id: `math-4-94`,
    case_id: `MATH 4.94`,
    title: `Log inequalities`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `If $\\log_{4} x = 5$, then $x$ is greater than $256$.`,
      `With $u=2^x>0$, the equation $3\\cdot4^x-27\\cdot2^x+54=0$ yields $5$ real solutions for $x$.`,
      `The equation $2^x = -5$ has no real solution.`,
      `Every real root of $2^{x+1} = 64$ satisfies $x$ equals $9$.`,
      `Every admissible root of $\\log_{4} x = 6$ satisfies $x$ equals $4099$.`,
    ],
    answer_key: [true, false, true, false, false],
    tactical_explanations: [
      `**A.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x > 256$.

$$x=4^{5}=1024$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Two positive $u$ → two $x$.

$$3u^2-27u+54=0$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$2^x > 0$$ always; RHS negative.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Match powers → $x=5$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$x=4^{6}=4096$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
    ],
    difficulty_level: `1/5`,
    sort_order: 94,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-95`,
    case_id: `MATH 4.95`,
    title: `Exam exponentials`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `A heated metal rod model satisfies $e^{2x} - 14e^x + 40 = 0$ with $u=e^x>0$. There are $5$ distinct real exponents $x$.`,
      `Every real root of $10^{x-1} = 1000$ satisfies $x$ is greater than $3$.`,
      `Every admissible root of $\\log_{5} x = 4$ satisfies $x$ equals $629$.`,
      `Every admissible root of $\\ln x = \\ln 4 + 2$ satisfies $x$ is greater than $28$.`,
      `Every positive root of $\\log x + \\log 4 = 5$ satisfies $x$ is greater than $\\frac{499984}{5}$.`,
    ],
    answer_key: [false, true, false, true, true],
    tactical_explanations: [
      `**A.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Two positive $u$ give two real $x$.

$$u^2-14u+40=0$$

$$(u-4)(u-10)=0$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**B.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Match powers → $x=4$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**C.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$x=5^{4}=625$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**D.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\ln x = \\ln(4e^{2})$$

$$x=29.56$$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**E.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\log(4x)=5$$

$$x=100000$$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `1/5`,
    sort_order: 95,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-96`,
    case_id: `MATH 4.96`,
    title: `Complex logarithms`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every admissible root of $\\log_{2} x = 7$ satisfies $x$ is greater than $\\frac{624}{5}$.`,
      `Every admissible root of $\\ln x = \\ln 5 + 3$ satisfies $x$ equals $103.43$.`,
      `Every positive root of $\\log x + \\log 5 = 6$ satisfies $x$ equals $1000004$.`,
      `For decadic logarithms, the unique admissible root of $\\log x^{1/6} - \\log x^{6} - \\log x^2 + \\frac{16}{3} = \\frac{2\\log x}{3}$ satisfies $x < 7$.`,
      `Every positive root of $\\log x + \\log(x+2) = 1$ satisfies $x$ equals $5.32$.`,
    ],
    answer_key: [true, false, false, true, false],
    tactical_explanations: [
      `**A.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$x=2^{7}=128$$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\ln x = \\ln(5e^{3})$$

$$x=100.43$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\log(5x)=6$$

$$x=1000000$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**D.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x < 7$.

$$\\left(\\frac{1}{6}-6-2\\right)\\log x + \\frac{16}{3} = \\frac{2}{3}\\log x$$

$$\\log x = -0.63$$

$$x \\approx 0.24$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**E.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Compare with the bound in the claim.

$$x(x+2)=10^{1}$$

$$x=2.32$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
    ],
    difficulty_level: `1/5`,
    sort_order: 96,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-97`,
    case_id: `MATH 4.97`,
    title: `Population growth`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every positive root of $\\log x + \\log 6 = 7$ satisfies $x$ equals $10000004$.`,
      `The solution of $\\log \\sqrt[3]{x} + \\log \\frac{1}{x^{3}} - \\log x^2 + \\frac{16}{3} = \\frac{\\log x^2}{1 + \\log 100}$, where $\\log x$ denotes the decadic logarithm of $x$, is smaller than $8$.`,
      `Every positive root of $\\log x + \\log(x+3) = 2$ satisfies $x$ is greater than $\\frac{41}{5}$.`,
      `Every real root of $4^x = 256$ satisfies $x$ equals $7$.`,
      `Measuring time after an offset, $\\ln(x-4)=\\ln 5$ holds for an admissible $x$ that is greater than $8$.`,
    ],
    answer_key: [false, true, true, false, true],
    tactical_explanations: [
      `**A.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\log(6x)=7$$

$$x=10000000$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**B.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x < 8$.

$$\\left(\\frac{1}{3}-3-2\\right)\\log x + \\frac{16}{3} = \\frac{2}{3}\\log x$$

$$\\log x = -1$$

$$x \\approx \\frac{1}{10}$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**C.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Compare with the bound in the claim.

$$x(x+3)=10^{2}$$

$$x=8.61$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Match powers → $x=4$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>4$.

$$x-4=5$$

$$x=9$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `1/5`,
    sort_order: 97,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-98`,
    case_id: `MATH 4.98`,
    title: `Compound and decay`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every positive root of $\\log x + \\log(x+4) = 1$ satisfies $x$ is greater than $\\frac{13}{10}$.`,
      `A heated metal rod model satisfies $e^{2x} - 8e^x + 12 = 0$ with $u=e^x>0$. There are more than $1$ distinct real exponents $x$.`,
      `Measuring time after an offset, $\\ln(x-7)=\\ln 2$ holds for an admissible $x$ that equals $11$.`,
      `Every admissible root of $\\log_{3} x + \\frac{\\log_{3} x}{3} = 5$ satisfies $x$ equals $64.55$.`,
      `Every real root of $9^x = 3^{x+2}$ satisfies $x$ equals $5$.`,
    ],
    answer_key: [true, true, false, false, false],
    tactical_explanations: [
      `**A.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Compare with the bound in the claim.

$$x(x+4)=10^{1}$$

$$x=1.74$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Two positive $u$ give two real $x$.

$$u^2-8u+12=0$$

$$(u-2)(u-6)=0$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**C.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>7$.

$$x-7=2$$

$$x=9$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**D.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\frac{4}{3}\\log_{3} x = 5$$

$$x=3^{\\frac{15}{4}}=61.55$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Rewrite with a common base and equate exponents:

$$3^{2x} = 3^{x+2}$$

$$2x = x+2$$

$$x = 2$$

Since $x=2$, compare with the bound in the claim.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
    ],
    difficulty_level: `1/5`,
    sort_order: 98,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-99`,
    case_id: `MATH 4.99`,
    title: `Substitution models`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Measuring time after an offset, $\\ln(x-5)=\\ln 3$ holds for an admissible $x$ that equals $11$.`,
      `Every admissible root of $\\log_{4} x + \\frac{\\log_{4} x}{2} = 6$ satisfies $x$ equals $259$.`,
      `Every real root of $25^x = 5^{x+3}$ satisfies $x$ is greater than $2$.`,
      `If $\\log_{2} x = 3$, then $x$ is greater than $4$.`,
      `With $u=2^x>0$, the equation $3\\cdot4^x-30\\cdot2^x+63=0$ yields more than $1$ real solutions for $x$.`,
    ],
    answer_key: [false, false, true, true, true],
    tactical_explanations: [
      `**A.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>5$.

$$x-5=3$$

$$x=8$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**B.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\frac{3}{2}\\log_{4} x = 6$$

$$x=4^{4}=256$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Rewrite with a common base and equate exponents:

$$5^{2x} = 5^{x+3}$$

$$2x = x+3$$

$$x = 3$$

Since $x=3$, compare with the bound in the claim.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x > 4$.

$$x=2^{3}=8$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**E.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Two positive $u$ → two $x$.

$$3u^2-30u+63=0$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `1/5`,
    sort_order: 99,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-100`,
    case_id: `MATH 4.100`,
    title: `Mixed bases`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every real root of $2^x = 3^{x-1}$ satisfies $x$ is greater than $0$.`,
      `With $u=2^x>0$, the equation $3\\cdot4^x-24\\cdot2^x+45=0$ yields $5$ real solutions for $x$.`,
      `The equation $2^x = -7$ has no real solution.`,
      `A heated metal rod model satisfies $e^{2x} - 8e^x + 12 = 0$ with $u=e^x>0$. There are $5$ distinct real exponents $x$.`,
      `Every real root of $4^x = 256$ satisfies $x$ is greater than $3$.`,
    ],
    answer_key: [true, false, true, false, true],
    tactical_explanations: [
      `**A.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Rewrite with a common base and equate exponents:

$$2^x = \\frac{3^x}{3}$$

$$\\left(\\frac{2}{3}\\right)^x = \\frac{1}{3}$$

$$x = 1$$

Since $x=1$, compare with the bound in the claim.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Two positive $u$ → two $x$.

$$3u^2-24u+45=0$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$2^x > 0$$ always; RHS negative.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Two positive $u$ give two real $x$.

$$u^2-8u+12=0$$

$$(u-2)(u-6)=0$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Match powers → $x=4$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `2/5`,
    sort_order: 100,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-101`,
    case_id: `MATH 4.101`,
    title: `Cooling law`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every positive root of $\\log x + \\log(x+4) = 1$ satisfies $x$ equals $4.74$.`,
      `A heated metal rod model satisfies $e^{2x} - 11e^x + 24 = 0$ with $u=e^x>0$. There are more than $1$ distinct real exponents $x$.`,
      `Every real root of $10^{x-1} = 1000$ satisfies $x$ equals $7$.`,
      `Every admissible root of $\\log_{4} x = 6$ satisfies $x$ is greater than $\\frac{20464}{5}$.`,
      `Every admissible root of $\\ln x = \\ln 3 + 5$ satisfies $x$ equals $448.24$.`,
    ],
    answer_key: [false, true, false, true, false],
    tactical_explanations: [
      `**A.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Compare with the bound in the claim.

$$x(x+4)=10^{1}$$

$$x=1.74$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**B.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Two positive $u$ give two real $x$.

$$u^2-11u+24=0$$

$$(u-3)(u-8)=0$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**C.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Match powers → $x=4$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**D.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$x=4^{6}=4096$$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**E.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\ln x = \\ln(3e^{5})$$

$$x=445.24$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
    ],
    difficulty_level: `2/5`,
    sort_order: 101,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-102`,
    case_id: `MATH 4.102`,
    title: `Log inequalities`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every real root of $3^x = 81$ satisfies $x$ is greater than $3$.`,
      `Every admissible root of $\\log_{5} x = 4$ satisfies $x$ is greater than $\\frac{3109}{5}$.`,
      `Every admissible root of $\\ln x = \\ln 4 + 2$ satisfies $x$ equals $32.56$.`,
      `Every positive root of $\\log x + \\log 4 = 5$ satisfies $x$ equals $100004$.`,
      `The solution of $\\log \\sqrt[5]{x} + \\log \\frac{1}{x^{5}} - \\log x^2 + \\frac{16}{3} = \\frac{\\log x^2}{1 + \\log 100}$, where $\\log x$ denotes the decadic logarithm of $x$, is smaller than $6$.`,
    ],
    answer_key: [true, true, false, false, true],
    tactical_explanations: [
      `**A.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Match powers → $x=4$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$x=5^{4}=625$$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**C.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\ln x = \\ln(4e^{2})$$

$$x=29.56$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**D.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\log(4x)=5$$

$$x=100000$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x < 6$.

$$\\left(\\frac{1}{5}-5-2\\right)\\log x + \\frac{16}{3} = \\frac{2}{3}\\log x$$

$$\\log x = -\\frac{5}{7}$$

$$x \\approx 0.19$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `2/5`,
    sort_order: 102,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-103`,
    case_id: `MATH 4.103`,
    title: `Exam exponentials`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every real root of $2^x = 3^{x-1}$ satisfies $x$ equals $4$.`,
      `A heated metal rod model satisfies $e^{2x} - 11e^x + 24 = 0$ with $u=e^x>0$. There are $5$ distinct real exponents $x$.`,
      `With $u=2^x>0$, the equation $2\\cdot4^x-16\\cdot2^x+24=0$ yields more than $1$ real solutions for $x$.`,
      `Every positive root of $\\log x + \\log(x+2) = 1$ satisfies $x$ is greater than $\\frac{19}{10}$.`,
      `Measuring time after an offset, $\\ln(x-6)=\\ln 5$ holds for an admissible $x$ that equals $14$.`,
    ],
    answer_key: [false, false, true, true, false],
    tactical_explanations: [
      `**A.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Rewrite with a common base and equate exponents:

$$2^x = \\frac{3^x}{3}$$

$$\\left(\\frac{2}{3}\\right)^x = \\frac{1}{3}$$

$$x = 1$$

Since $x=1$, compare with the bound in the claim.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**B.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Two positive $u$ give two real $x$.

$$u^2-11u+24=0$$

$$(u-3)(u-8)=0$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Two positive $u$ → two $x$.

$$2u^2-16u+24=0$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Compare with the bound in the claim.

$$x(x+2)=10^{1}$$

$$x=2.32$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**E.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>6$.

$$x-6=5$$

$$x=11$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
    ],
    difficulty_level: `2/5`,
    sort_order: 103,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-104`,
    case_id: `MATH 4.104`,
    title: `Complex logarithms`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `The equation $3^x = -6$ has no real solution.`,
      `Every positive root of $\\log x + \\log(x+3) = 2$ satisfies $x$ equals $11.61$.`,
      `Every real root of $2^x = 32$ satisfies $x$ equals $9$.`,
      `Every admissible root of $\\log_{4} x = 7$ satisfies $x$ is greater than $\\frac{81904}{5}$.`,
      `Every admissible root of $\\log_{2} x + \\frac{\\log_{2} x}{2} = 4$ satisfies $x$ is greater than $\\frac{59}{10}$.`,
    ],
    answer_key: [true, false, false, true, true],
    tactical_explanations: [
      `**A.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$3^x > 0$$ always; RHS negative.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Compare with the bound in the claim.

$$x(x+3)=10^{2}$$

$$x=8.61$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Match powers → $x=5$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**D.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$x=4^{7}=16384$$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**E.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\frac{3}{2}\\log_{2} x = 4$$

$$x=2^{\\frac{8}{3}}=6.35$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `2/5`,
    sort_order: 104,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-105`,
    case_id: `MATH 4.105`,
    title: `Population growth`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every real root of $3^x = 81$ satisfies $x$ equals $7$.`,
      `Measuring time after an offset, $\\ln(x-7)=\\ln 2$ holds for an admissible $x$ that is greater than $8$.`,
      `Every admissible root of $\\log_{3} x + \\frac{\\log_{3} x}{3} = 5$ satisfies $x$ is greater than $\\frac{292}{5}$.`,
      `With $u=2^x>0$, the equation $2\\cdot4^x-16\\cdot2^x+24=0$ yields $5$ real solutions for $x$.`,
      `Every admissible root of $\\log_{5} x = 7$ satisfies $x$ equals $78129$.`,
    ],
    answer_key: [false, true, true, false, false],
    tactical_explanations: [
      `**A.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Match powers → $x=4$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**B.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>7$.

$$x-7=2$$

$$x=9$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**C.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\frac{4}{3}\\log_{3} x = 5$$

$$x=3^{\\frac{15}{4}}=61.55$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Two positive $u$ → two $x$.

$$2u^2-16u+24=0$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$x=5^{7}=78125$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
    ],
    difficulty_level: `3/5`,
    sort_order: 105,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-106`,
    case_id: `MATH 4.106`,
    title: `Compound and decay`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every admissible root of $\\log_{4} x + \\frac{\\log_{4} x}{2} = 6$ satisfies $x$ is greater than $\\frac{1264}{5}$.`,
      `Every real root of $25^x = 5^{x+3}$ satisfies $x$ equals $5$.`,
      `For decadic logarithms, the unique admissible root of $\\log x^{1/6} - \\log x^{6} - \\log x^2 + \\frac{16}{3} = \\frac{2\\log x}{3}$ satisfies $x < 5$.`,
      `The equation $5^x = -4$ has no real solution.`,
      `Measuring time after an offset, $\\ln(x-7)=\\ln 5$ holds for an admissible $x$ that equals $14$.`,
    ],
    answer_key: [true, false, true, true, false],
    tactical_explanations: [
      `**A.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\frac{3}{2}\\log_{4} x = 6$$

$$x=4^{4}=256$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Rewrite with a common base and equate exponents:

$$5^{2x} = 5^{x+3}$$

$$2x = x+3$$

$$x = 3$$

Since $x=3$, compare with the bound in the claim.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x < 5$.

$$\\left(\\frac{1}{6}-6-2\\right)\\log x + \\frac{16}{3} = \\frac{2}{3}\\log x$$

$$\\log x = -0.63$$

$$x \\approx 0.24$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$5^x > 0$$ always; RHS negative.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**E.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>7$.

$$x-7=5$$

$$x=12$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
    ],
    difficulty_level: `3/5`,
    sort_order: 106,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-107`,
    case_id: `MATH 4.107`,
    title: `Substitution models`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every real root of $5^x = 625$ satisfies $x$ equals $7$.`,
      `With $u=2^x>0$, the equation $2\\cdot4^x-14\\cdot2^x+20=0$ yields more than $1$ real solutions for $x$.`,
      `Measuring time after an offset, $\\ln(x-5)=\\ln 2$ holds for an admissible $x$ that equals $10$.`,
      `Every admissible root of $\\log_{4} x = 3$ satisfies $x$ equals $67$.`,
      `Every admissible root of $\\log_{3} x + \\frac{\\log_{3} x}{2} = 5$ satisfies $x$ is greater than $\\frac{73}{2}$.`,
    ],
    answer_key: [false, true, false, false, true],
    tactical_explanations: [
      `**A.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Match powers → $x=4$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**B.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Two positive $u$ → two $x$.

$$2u^2-14u+20=0$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**C.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>5$.

$$x-5=2$$

$$x=7$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**D.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$x=4^{3}=64$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\frac{3}{2}\\log_{3} x = 5$$

$$x=3^{\\frac{10}{3}}=38.94$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `3/5`,
    sort_order: 107,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-108`,
    case_id: `MATH 4.108`,
    title: `Mixed bases`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every real root of $5^x = 625$ satisfies $x$ is greater than $3$.`,
      `Measuring time after an offset, $\\ln(x-8)=\\ln 2$ holds for an admissible $x$ that is greater than $9$.`,
      `Every admissible root of $\\log_{4} x + \\frac{\\log_{4} x}{3} = 6$ satisfies $x$ is greater than $\\frac{2544}{5}$.`,
      `With $u=2^x>0$, the equation $2\\cdot4^x-18\\cdot2^x+28=0$ yields $5$ real solutions for $x$.`,
      `Every positive root of $\\log x + \\log 3 = 4$ satisfies $x$ equals $10004$.`,
    ],
    answer_key: [true, true, true, false, false],
    tactical_explanations: [
      `**A.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Match powers → $x=4$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>8$.

$$x-8=2$$

$$x=10$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**C.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\frac{4}{3}\\log_{4} x = 6$$

$$x=4^{\\frac{9}{2}}=512$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Two positive $u$ → two $x$.

$$2u^2-18u+28=0$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\log(3x)=4$$

$$x=10000$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
    ],
    difficulty_level: `3/5`,
    sort_order: 108,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-109`,
    case_id: `MATH 4.109`,
    title: `Cooling law`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every admissible root of $\\log_{2} x + \\frac{\\log_{2} x}{2} = 4$ satisfies $x$ equals $9.35$.`,
      `Measuring time after an offset, $\\ln(x-8)=\\ln 4$ holds for an admissible $x$ that equals $14$.`,
      `With $u=2^x>0$, the equation $2\\cdot4^x-14\\cdot2^x+20=0$ yields $5$ real solutions for $x$.`,
      `The equation $5^x = -5$ has no real solution.`,
      `Every positive root of $\\log x + \\log(x+5) = 2$ satisfies $x$ is greater than $\\frac{37}{5}$.`,
    ],
    answer_key: [false, false, false, true, true],
    tactical_explanations: [
      `**A.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\frac{3}{2}\\log_{2} x = 4$$

$$x=2^{\\frac{8}{3}}=6.35$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**B.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>8$.

$$x-8=4$$

$$x=12$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Two positive $u$ → two $x$.

$$2u^2-14u+20=0$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**D.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$5^x > 0$$ always; RHS negative.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**E.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Compare with the bound in the claim.

$$x(x+5)=10^{2}$$

$$x=7.81$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `3/5`,
    sort_order: 109,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-110`,
    case_id: `MATH 4.110`,
    title: `Log inequalities`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every positive root of $\\log x + \\log 5 = 6$ satisfies $x$ is greater than $\\frac{4999984}{5}$.`,
      `Measuring time after an offset, $\\ln(x-6)=\\ln 3$ holds for an admissible $x$ that equals $11$.`,
      `Every admissible root of $\\ln x = \\ln 3 + 3$ satisfies $x$ equals $63.26$.`,
      `Every admissible root of $\\log_{4} x = 4$ satisfies $x$ equals $259$.`,
      `Every real root of $9^x = 3^{x+2}$ satisfies $x$ is greater than $1$.`,
    ],
    answer_key: [true, false, false, false, true],
    tactical_explanations: [
      `**A.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\log(5x)=6$$

$$x=1000000$$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>6$.

$$x-6=3$$

$$x=9$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\ln x = \\ln(3e^{3})$$

$$x=60.26$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**D.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$x=4^{4}=256$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Rewrite with a common base and equate exponents:

$$3^{2x} = 3^{x+2}$$

$$2x = x+2$$

$$x = 2$$

Since $x=2$, compare with the bound in the claim.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `3/5`,
    sort_order: 110,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-111`,
    case_id: `MATH 4.111`,
    title: `Exam exponentials`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `With $u=2^x>0$, the equation $3\\cdot4^x-30\\cdot2^x+63=0$ yields $5$ real solutions for $x$.`,
      `For decadic logarithms, the unique admissible root of $\\log x^{1/4} - \\log x^{4} - \\log x^2 + \\frac{16}{3} = \\frac{2\\log x}{3}$ satisfies $x < 7$.`,
      `Measuring time after an offset, $\\ln(x-8)=\\ln 4$ holds for an admissible $x$ that is greater than $10$.`,
      `If $\\log_{3} x = 4$, then $x$ is greater than $27$.`,
      `Every real root of $4^x = 2^{x+4}$ satisfies $x$ equals $7$.`,
    ],
    answer_key: [false, true, true, true, false],
    tactical_explanations: [
      `**A.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Two positive $u$ → two $x$.

$$3u^2-30u+63=0$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**B.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x < 7$.

$$\\left(\\frac{1}{4}-4-2\\right)\\log x + \\frac{16}{3} = \\frac{2}{3}\\log x$$

$$\\log x = -0.83$$

$$x \\approx 0.15$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**C.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>8$.

$$x-8=4$$

$$x=12$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x > 27$.

$$x=3^{4}=81$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**E.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Rewrite with a common base and equate exponents:

$$2^{2x} = 2^{x+4}$$

$$2x = x+4$$

$$x = 4$$

Since $x=4$, compare with the bound in the claim.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
    ],
    difficulty_level: `4/5`,
    sort_order: 111,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-112`,
    case_id: `MATH 4.112`,
    title: `Complex logarithms`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every admissible root of $\\log_{5} x = 5$ satisfies $x$ is greater than $\\frac{15609}{5}$.`,
      `Every admissible root of $\\ln x = \\ln 5 + 2$ satisfies $x$ is greater than $\\frac{173}{5}$.`,
      `Measuring time after an offset, $\\ln(x-4)=\\ln 3$ holds for an admissible $x$ that equals $10$.`,
      `Every real root of $4^x = 2^{x+4}$ satisfies $x$ is greater than $3$.`,
      `The solution of the equation $\\log \\sqrt[5]{x} + \\log \\frac{1}{x^{5}} - \\log x^2 + \\frac{16}{3} = \\frac{\\log x^2}{1 + \\log 100}$, where $\\log x$ denotes the decadic logarithm of $x$, is not smaller than $12$.`,
    ],
    answer_key: [true, true, false, true, false],
    tactical_explanations: [
      `**A.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$x=5^{5}=3125$$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\ln x = \\ln(5e^{2})$$

$$x=36.95$$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**C.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>4$.

$$x-4=3$$

$$x=7$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**D.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Rewrite with a common base and equate exponents:

$$2^{2x} = 2^{x+4}$$

$$2x = x+4$$

$$x = 4$$

Since $x=4$, compare with the bound in the claim.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**E.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Use $\\log 100=2$ on the right-hand side.

$$\\log x = 0.4$$

$$x = 10^{0.4} = 2.51$$

Combine coefficients of $\\log x$ on the left:

$x < 12$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
    ],
    difficulty_level: `4/5`,
    sort_order: 112,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-113`,
    case_id: `MATH 4.113`,
    title: `Population growth`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Measuring time after an offset, $\\ln(x-7)=\\ln 4$ holds for an admissible $x$ that equals $14$.`,
      `The solution of the equation $\\log \\sqrt[4]{x} + \\log \\frac{1}{x^{4}} - \\log x^2 + \\frac{16}{3} = \\frac{\\log x^2}{1 + \\log 100}$, where $\\log x$ denotes the decadic logarithm of $x$, is not smaller than $8$.`,
      `A heated metal rod model satisfies $e^{2x} - 14e^x + 40 = 0$ with $u=e^x>0$. There are more than $1$ distinct real exponents $x$.`,
      `Every admissible root of $\\log_{3} x + \\frac{\\log_{3} x}{2} = 5$ satisfies $x$ equals $41.94$.`,
      `With $u=2^x>0$, the equation $3\\cdot4^x-24\\cdot2^x+45=0$ yields more than $1$ real solutions for $x$.`,
    ],
    answer_key: [false, false, true, false, true],
    tactical_explanations: [
      `**A.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>7$.

$$x-7=4$$

$$x=11$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**B.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Use $\\log 100=2$ on the right-hand side.

$$\\log x = 0.5$$

$$x = 10^{0.5} = 3.16$$

Combine coefficients of $\\log x$ on the left:

$x < 8$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Two positive $u$ give two real $x$.

$$u^2-14u+40=0$$

$$(u-4)(u-10)=0$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\frac{3}{2}\\log_{3} x = 5$$

$$x=3^{\\frac{10}{3}}=38.94$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Two positive $u$ → two $x$.

$$3u^2-24u+45=0$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `4/5`,
    sort_order: 113,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-114`,
    case_id: `MATH 4.114`,
    title: `Compound and decay`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every admissible root of $\\log_{2} x + \\frac{\\log_{2} x}{3} = 4$ satisfies $x$ is greater than $\\frac{38}{5}$.`,
      `Every admissible root of $\\log_{5} x = 3$ satisfies $x$ equals $129$.`,
      `For decadic logarithms, the unique admissible root of $\\log x^{1/6} - \\log x^{6} - \\log x^2 + \\frac{16}{3} = \\frac{2\\log x}{3}$ satisfies $x < 9$.`,
      `Measuring time after an offset, $\\ln(x-8)=\\ln 2$ holds for an admissible $x$ that equals $14$.`,
      `Every admissible root of $\\ln x = \\ln 5 + 4$ satisfies $x$ equals $275.99$.`,
    ],
    answer_key: [true, false, true, false, false],
    tactical_explanations: [
      `**A.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\frac{4}{3}\\log_{2} x = 4$$

$$x=2^{3}=8$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$x=5^{3}=125$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x < 9$.

$$\\left(\\frac{1}{6}-6-2\\right)\\log x + \\frac{16}{3} = \\frac{2}{3}\\log x$$

$$\\log x = -0.63$$

$$x \\approx 0.24$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>8$.

$$x-8=2$$

$$x=10$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\ln x = \\ln(5e^{4})$$

$$x=272.99$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
    ],
    difficulty_level: `4/5`,
    sort_order: 114,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-115`,
    case_id: `MATH 4.115`,
    title: `Substitution models`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Measuring time after an offset, $\\ln(x-6)=\\ln 4$ holds for an admissible $x$ that equals $14$.`,
      `Every admissible root of $\\ln x = \\ln 3 + 2$ satisfies $x$ is greater than $21$.`,
      `Every admissible root of $\\log_{2} x = 3$ satisfies $x$ equals $11$.`,
      `Every positive root of $\\log x + \\log 3 = 4$ satisfies $x$ is greater than $\\frac{49984}{5}$.`,
      `For decadic logarithms, the unique admissible root of $\\log x^{1/4} - \\log x^{4} - \\log x^2 + \\frac{16}{3} = \\frac{2\\log x}{3}$ satisfies $x < 5$.`,
    ],
    answer_key: [false, true, false, true, true],
    tactical_explanations: [
      `**A.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>6$.

$$x-6=4$$

$$x=10$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**B.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\ln x = \\ln(3e^{2})$$

$$x=22.17$$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**C.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$x=2^{3}=8$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**D.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\log(3x)=4$$

$$x=10000$$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**E.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x < 5$.

$$\\left(\\frac{1}{4}-4-2\\right)\\log x + \\frac{16}{3} = \\frac{2}{3}\\log x$$

$$\\log x = -0.83$$

$$x \\approx 0.15$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `4/5`,
    sort_order: 115,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-116`,
    case_id: `MATH 4.116`,
    title: `Mixed bases`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `The solution of the equation $\\log \\sqrt[3]{x} + \\log \\frac{1}{x^{3}} - \\log x^2 + \\frac{16}{3} = \\frac{\\log x^2}{1 + \\log 100}$, where $\\log x$ denotes the decadic logarithm of $x$, is not smaller than $5$.`,
      `The solution of the equation $\\log \\sqrt[3]{x} + \\log \\frac{1}{x^{3}} - \\log x^2 + \\frac{16}{3} = \\frac{\\log x^2}{1 + \\log 100}$, where $\\log x$ denotes the decadic logarithm of $x$, is smaller than $5$.`,
      `A heated metal rod model leads to $e^{2x} - 10e^x + 21 = 0$ after substitution $u=e^x$ with $u>0$. There are $5$ distinct real values of $x$.`,
      `With $u=2^x>0$, the equation $3\\cdot4^x-27\\cdot2^x+54=0$ yields more than $1$ real solutions for $x$.`,
      `Every admissible root of $\\log_{2} x + \\frac{\\log_{2} x}{3} = 4$ satisfies $x$ equals $11$.`,
    ],
    answer_key: [true, false, false, true, false],
    tactical_explanations: [
      `**A.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>0$. With $\\log 100=2$:

$$\\left(\\frac{1}{3}-3-2\\right)\\log x + \\frac{16}{3} = \\frac{2}{3}\\log x$$

$$\\log x = 1$$

$$x = 10$$

$10 \\ge 5$, so the root is not smaller than $5$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Use $\\log 100=2$ on the right-hand side.

$$\\log x = 1$$

$$x = 10^{1} = 10$$

Combine coefficients of $\\log x$ on the left:

$x \\ge 5$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Two positive $u$ give two real $x$.

$$u^2-10u+21=0$$

$$(u-3)(u-7)=0$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**D.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Two positive $u$ → two $x$.

$$3u^2-27u+54=0$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**E.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\frac{4}{3}\\log_{2} x = 4$$

$$x=2^{3}=8$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
    ],
    difficulty_level: `5/5`,
    sort_order: 116,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-117`,
    case_id: `MATH 4.117`,
    title: `Cooling law`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Every positive root of $\\log x + \\log(x+3) = 1$ satisfies $x$ equals $5$.`,
      `A heated metal rod model leads to $e^{2x} - 10e^x + 21 = 0$ after substitution $u=e^x$ with $u>0$. There are more than $1$ distinct real values of $x$.`,
      `Measuring time after an offset, $\\ln(x-6)=\\ln 5$ holds for an admissible $x$ that is greater than $10$.`,
      `Every admissible root of $\\log_{4} x + \\frac{\\log_{4} x}{3} = 6$ satisfies $x$ equals $515$.`,
      `The solution of the equation $\\log \\sqrt[5]{x} + \\log \\frac{1}{x^{5}} - \\log x^2 + \\frac{16}{3} = \\frac{\\log x^2}{1 + \\log 100}$, where $\\log x$ denotes the decadic logarithm of $x$, is smaller than $12$.`,
    ],
    answer_key: [false, true, true, false, true],
    tactical_explanations: [
      `**A.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\log(x(x+3))=1$$

$$x(x+3)=10$$

$$x=2$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**B.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Two positive $u$ give two real $x$.

$$u^2-10u+21=0$$

$$(u-3)(u-7)=0$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**C.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>6$.

$$x-6=5$$

$$x=11$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\frac{4}{3}\\log_{4} x = 6$$

$$x=4^{\\frac{9}{2}}=512$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Use $\\log 100=2$ on the right-hand side.

$$\\log x = 0.4$$

$$x = 10^{0.4} = 2.51$$

Combine coefficients of $\\log x$ on the left:

$x < 12$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `5/5`,
    sort_order: 117,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-118`,
    case_id: `MATH 4.118`,
    title: `Log inequalities`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `The solution of the equation $\\log \\sqrt[4]{x} + \\log \\frac{1}{x^{4}} - \\log x^2 + \\frac{16}{3} = \\frac{\\log x^2}{1 + \\log 100}$, where $\\log x$ denotes the decadic logarithm of $x$, is smaller than $8$.`,
      `Every positive root of $\\log x + \\log(x+3) = 1$ satisfies $x$ is greater than $1$.`,
      `Every admissible root of $\\ln x = \\ln 4 + 5$ satisfies $x$ equals $596.65$.`,
      `Measuring time after an offset, $\\ln(x-4)=\\ln 2$ holds for an admissible $x$ that equals $8$.`,
      `Every positive root of $\\log x + \\log(x+5) = 2$ satisfies $x$ equals $10.81$.`,
    ],
    answer_key: [true, true, false, false, false],
    tactical_explanations: [
      `**A.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Use $\\log 100=2$ on the right-hand side.

$$\\log x = 0.5$$

$$x = 10^{0.5} = 3.16$$

Combine coefficients of $\\log x$ on the left:

$x < 8$.

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Work from the story to a single equation, then solve:

$$\\log(x(x+3))=1$$

$$x(x+3)=10$$

$$x=2$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**C.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$\\ln x = \\ln(4e^{5})$$

$$x=593.65$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**D.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>4$.

$$x-4=2$$

$$x=6$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Compare with the bound in the claim.

$$x(x+5)=10^{2}$$

$$x=7.81$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
    ],
    difficulty_level: `5/5`,
    sort_order: 118,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-119`,
    case_id: `MATH 4.119`,
    title: `Exam exponentials`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `Measuring time after an offset, $\\ln(x-8)=\\ln 3$ holds for an admissible $x$ that equals $14$.`,
      `Every admissible root of $\\log_{2} x = 7$ satisfies $x$ equals $131$.`,
      `With $u=2^x>0$, the equation $2\\cdot4^x-18\\cdot2^x+28=0$ yields more than $1$ real solutions for $x$.`,
      `The solution of $\\log \\sqrt[5]{x} + \\log \\frac{1}{x^{5}} - \\log x^2 + \\frac{16}{3} = \\frac{\\log x^2}{1 + \\log 100}$, where $\\log x$ denotes the decadic logarithm of $x$, is smaller than $8$.`,
      `Measuring time after an offset, $\\ln(x-5)=\\ln 5$ holds for an admissible $x$ that is greater than $9$.`,
    ],
    answer_key: [false, false, true, true, true],
    tactical_explanations: [
      `**A.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>8$.

$$x-8=3$$

$$x=11$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**B.** → False

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Work from the story to a single equation, then solve:

$$x=2^{7}=128$$.

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

Two positive $u$ → two $x$.

$$2u^2-18u+28=0$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x < 8$.

$$\\left(\\frac{1}{5}-5-2\\right)\\log x + \\frac{16}{3} = \\frac{2}{3}\\log x$$

$$\\log x = -\\frac{5}{7}$$

$$x \\approx 0.19$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**E.** → True

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>5$.

$$x-5=5$$

$$x=10$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `5/5`,
    sort_order: 119,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
  {
    id: `math-4-120`,
    case_id: `MATH 4.120`,
    title: `Complex logarithms`,
    subsection: `4.4`,
    context: `Evaluate each statement. Mark it TRUE or FALSE.`,
    statements: [
      `The solution of $\\log \\sqrt[3]{x} + \\log \\frac{1}{x^{3}} - \\log x^2 + \\frac{16}{3} = \\frac{\\log x^2}{1 + \\log 100}$, where $\\log x$ denotes the decadic logarithm of $x$, is smaller than $4$.`,
      `Measuring time after an offset, $\\ln(x-4)=\\ln 5$ holds for an admissible $x$ that equals $11$.`,
      `The solution of $\\log \\sqrt[3]{x} + \\log \\frac{1}{x^{3}} - \\log x^2 + \\frac{16}{3} = \\frac{\\log x^2}{1 + \\log 100}$, where $\\log x$ denotes the decadic logarithm of $x$, is smaller than $6$.`,
      `Measuring time after an offset, $\\ln(x-6)=\\ln 2$ holds for an admissible $x$ that equals $11$.`,
      `For decadic logarithms, the unique admissible root of $\\log x^{1/4} - \\log x^{4} - \\log x^2 + \\frac{16}{3} = \\frac{2\\log x}{3}$ satisfies $x < 9$.`,
    ],
    answer_key: [true, false, true, false, true],
    tactical_explanations: [
      `**A.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x < 4$.

$$\\left(\\frac{1}{3}-3-2\\right)\\log x + \\frac{16}{3} = \\frac{2}{3}\\log x$$

$$\\log x = -1$$

$$x \\approx \\frac{1}{10}$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**B.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>4$.

$$x-4=5$$

$$x=9$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**C.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x < 6$.

$$\\left(\\frac{1}{3}-3-2\\right)\\log x + \\frac{16}{3} = \\frac{2}{3}\\log x$$

$$\\log x = -1$$

$$x \\approx \\frac{1}{10}$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
      `**D.** → False

Use log and exponential laws to reduce the equation to a single logarithm or power. Respect the domain, solve for the variable, then compare with the claim.

Set up the model and solve:

Domain requires $x>6$.

$$x-6=2$$

$$x=8$$

The value recovered from the model contradicts the claim.

Matching the solved value to the claim, the statement is False.`,
      `**E.** → True

Translate the wording into one linear equation in a single unknown. Isolate the variable and compare the recovered value with the closing claim.

Set up the model and solve:

$x < 9$.

$$\\left(\\frac{1}{4}-4-2\\right)\\log x + \\frac{16}{3} = \\frac{2}{3}\\log x$$

$$\\log x = -0.83$$

$$x \\approx 0.15$$

The value recovered from the model satisfies the inequality in the claim.

Matching the solved value to the claim, the statement is True.`,
    ],
    difficulty_level: `5/5`,
    sort_order: 120,
    solution_overview: `Five independent exponential and logarithmic stories. Simplify log laws, respect domains and monotonicity, and compute before judging the final comparison.`,
  },
];
